// configs/ft232rl-config.js
// FTDI FT232RL — USB to Serial UART Interface IC
// Package: SSOP-28 (rendered as DIP-28)

window.IC_CONFIG = {

  // ── IDENTITY ──────────────────────────────────────────────────
  partName:     'FT232RL',
  partMPN:      'FT232RL',
  manufacturer: 'FTDI',
  package:      'DIP-28',
  pinCount:     28,

  // ── LINKS ─────────────────────────────────────────────────────
  snapPageURL:  'https://www.snapeda.com/parts/FT232RL/FTDI/view-part/',
  downloadURL:  'https://www.snapeda.com/parts/FT232RL/FTDI/view-part/?ref=snapeda',
  datasheetURL: 'https://ftdichip.com/wp-content/uploads/2020/08/DS_FT232R.pdf',

  // ── LAYOUT HINT (DIP-28) ──────────────────────────────────────
  dipConfig: {
    pinsPerSide:  14,
    bodyX:        122, bodyY: 25, bodyW: 260, bodyH: 490,
    pinLength:    34,  pinWidthHalf: 16,
    notchSize:    8,   notchX: 14, notchY: 14,
    textSizes:    { mfr: 14, part: 22, pkg: 14, pinCount: 12 },
    labelSize:    11,  pinNumSize: 14, yOffset: -40,
  },

  // ── CUSTOM TYPES ──────────────────────────────────────────────
  // FT232RL has modem-control and clock-output pins not in the standard set
  customTypes: {
    MODEM: { c: '#f4a261', bg: 'rgba(244,162,97,.12)',  bd: 'rgba(244,162,97,.35)' },
    CLK:   { c: '#7090a8', bg: 'rgba(112,144,168,.12)', bd: 'rgba(112,144,168,.35)' },
    EE:    { c: '#9898d8', bg: 'rgba(152,152,216,.12)', bd: 'rgba(152,152,216,.32)' },
    TEST:  { c: '#a8a8a8', bg: 'rgba(168,168,168,.10)', bd: 'rgba(168,168,168,.28)' },
  },

  // ── FILTER BUTTONS ────────────────────────────────────────────
  filterButtons: [
    { type: 'USB',   label: 'USB',              color: '#4a9aee' },
    { type: 'UART',  label: 'UART(TX/RX)',      color: '#cc6888', fontSize:'11' },
    { type: 'MODEM', label: 'Modem Control',     color: '#f4a261', fontSize:'10' },
    { type: 'CLK',   label: 'Clock Out',         color: '#7090a8', fontSize:'12' },
    { type: 'EE',    label: 'EEPROM',            color: '#9898d8' },
    { type: 'RESET', label: 'Reset',             color: '#ff9944' },
    { type: 'TEST',  label: 'Test',              color: '#a8a8a8' },
    { type: 'PWR',   label: 'Power',             color: '#ff6b6b' },
    { type: 'GND',   label: 'GND',               color: '#a8a8a8' },
  ],

  // ── PINS ──────────────────────────────────────────────────────
  // Left side: pins 1–14 (top→bottom), Right side: pins 15–28 (_rightSlot 0=top-right)
  pins: [
    // ── LEFT SIDE (pins 1–14, top → bottom) ───────────────────
    {
      num:   1,
      id:    'TXD',
      lbl:   'TXD',
      name:  'Transmit Data (UART)',
      type:  'UART',
      funcs: ['UART'],
      volt:  '3.3V / 5V',
      curr:  '±6 mA',
      note:  'Asynchronous data transmit output. Transmits serial data to the external device. Driven by the internal UART transmit shift register.',
    },
    {
      num:   2,
      id:    'DTR',
      lbl:   'DTR#',
      name:  'Data Terminal Ready (active low)',
      type:  'MODEM',
      funcs: ['MODEM'],
      volt:  '3.3V / 5V',
      curr:  '±6 mA',
      note:  'Modem handshake output, active low. Used to signal to a modem or peripheral that the host is ready to communicate. Can also function as a general-purpose output.',
    },
    {
      num:   3,
      id:    'RTS',
      lbl:   'RTS#',
      name:  'Request To Send (active low)',
      type:  'MODEM',
      funcs: ['MODEM'],
      volt:  '3.3V / 5V',
      curr:  '±6 mA',
      note:  'Modem handshake output, active low. Indicates the FT232RL is ready to receive data. Part of RTS/CTS hardware flow control.',
    },
    {
      num:   4,
      id:    'VCCIO',
      lbl:   'VCCIO',
      name:  'I/O Supply Voltage',
      type:  'PWR',
      funcs: ['PWR'],
      volt:  '1.8V–5.25V',
      curr:  '—',
      note:  'Supply voltage for the UART and control signal I/O pins. Can be set independently from VCC to allow interfacing with 1.8V, 2.5V, 3.3V, or 5V logic systems.',
    },
    {
      num:   5,
      id:    'RXD',
      lbl:   'RXD',
      name:  'Receive Data (UART)',
      type:  'UART',
      funcs: ['UART'],
      volt:  '3.3V / 5V',
      curr:  '—',
      note:  'Asynchronous data receive input. Receives serial data from the external device into the internal UART receive shift register. Input-only pin.',
    },
    {
      num:   6,
      id:    'RI',
      lbl:   'RI#',
      name:  'Ring Indicator (active low)',
      type:  'MODEM',
      funcs: ['MODEM'],
      volt:  '3.3V / 5V',
      curr:  '—',
      note:  'Modem status input, active low. Indicates an incoming call (ring signal) from a modem. Can also be used as a general-purpose input.',
    },
    {
      num:   7,
      id:    'GND1',
      lbl:   'GND',
      name:  'Ground',
      type:  'GND',
      funcs: ['GND'],
      volt:  '0V',
      curr:  '—',
      note:  'Ground reference for the device. Connect to the system ground plane.',
    },
    {
      num:   8,
      id:    'OSCI',
      lbl:   'OSCI',
      name:  'Internal Oscillator Input (no connect)',
      type:  'CLK',
      funcs: ['CLK'],
      volt:  '—',
      curr:  '—',
      note:  'Internal oscillator pin. The FT232RL has a built-in 12 MHz oscillator so no external crystal is required. This pin should be left unconnected (NC) in normal use.',
    },
    {
      num:   9,
      id:    'OSCO',
      lbl:   'OSCO',
      name:  'Internal Oscillator Output (no connect)',
      type:  'CLK',
      funcs: ['CLK'],
      volt:  '—',
      curr:  '—',
      note:  'Internal oscillator output pin. Leave unconnected (NC) in normal use. The on-chip 12 MHz oscillator eliminates the need for an external clock source.',
    },
    {
      num:   10,
      id:    'nRESET',
      lbl:   'RESET#',
      name:  'USB Reset (active low, open drain)',
      type:  'RESET',
      funcs: ['RESET'],
      volt:  '3.3V',
      curr:  '—',
      note:  'Active-low asynchronous reset input. Resets the device when pulled low. Can be driven by an external reset source or left unconnected — an internal pull-up holds it high during normal operation.',
    },
    {
      num:   11,
      id:    'GND2',
      lbl:   'GND',
      name:  'Ground',
      type:  'GND',
      funcs: ['GND'],
      volt:  '0V',
      curr:  '—',
      note:  'Ground reference for the device. Connect to the system ground plane.',
    },
    {
      num:   12,
      id:    'NC1',
      lbl:   'NC',
      name:  'No Connect',
      type:  'TEST',
      funcs: ['TEST'],
      volt:  '—',
      curr:  '—',
      note:  'No connect pin. Leave unconnected in all designs.',
    },
    {
      num:   13,
      id:    'USBDP',
      lbl:   'USBDP',
      name:  'USB Data Plus (D+)',
      type:  'USB',
      funcs: ['USB'],
      volt:  '3.3V',
      curr:  '—',
      note:  'USB 2.0 full-speed differential data line D+. Connect directly to the USB connector D+ pin with a 27Ω series resistor as recommended in the FTDI application notes.',
    },
    {
      num:   14,
      id:    'USBDM',
      lbl:   'USBDM',
      name:  'USB Data Minus (D−)',
      type:  'USB',
      funcs: ['USB'],
      volt:  '3.3V',
      curr:  '—',
      note:  'USB 2.0 full-speed differential data line D−. Connect directly to the USB connector D− pin with a 27Ω series resistor as recommended in the FTDI application notes.',
    },

    // ── RIGHT SIDE (pins 15–28, _rightSlot 0=top-right → 13=bottom-right) ──
    {
      num:   15,
      id:    'VCC3V3',
      lbl:   '3V3OUT',
      name:  '3.3V Regulator Output',
      type:  'PWR',
      funcs: ['PWR'],
      volt:  '3.3V',
      curr:  '50 mA max',
      note:  'Output of the internal 3.3V LDO regulator. Can supply up to 50 mA for external circuitry such as decoupling the USB pull-up resistor or powering low-current peripherals. Decouple with a 100 nF capacitor.',
      _rightSlot: 0,
    },
    {
      num:   16,
      id:    'GND3',
      lbl:   'GND',
      name:  'Ground',
      type:  'GND',
      funcs: ['GND'],
      volt:  '0V',
      curr:  '—',
      note:  'Ground reference for the device. Connect to the system ground plane.',
      _rightSlot: 1,
    },
    {
      num:   17,
      id:    'VCC',
      lbl:   'VCC',
      name:  'Device Supply Voltage',
      type:  'PWR',
      funcs: ['PWR'],
      volt:  '4.0V–5.25V',
      curr:  '—',
      note:  'Main supply voltage for the FT232RL. Typically 5V supplied from the USB bus or an external regulator. Decouple with 100 nF and 4.7 µF capacitors close to the pin.',
      _rightSlot: 2,
    },
    {
      num:   18,
      id:    'GND4',
      lbl:   'GND',
      name:  'Ground',
      type:  'GND',
      funcs: ['GND'],
      volt:  '0V',
      curr:  '—',
      note:  'Ground reference for the device. Connect to the system ground plane.',
      _rightSlot: 3,
    },
    {
      num:   19,
      id:    'NC2',
      lbl:   'NC',
      name:  'No Connect',
      type:  'TEST',
      funcs: ['TEST'],
      volt:  '—',
      curr:  '—',
      note:  'No connect pin. Leave unconnected in all designs.',
      _rightSlot: 4,
    },
    {
      num:   20,
      id:    'AGND',
      lbl:   'AGND',
      name:  'Analog Ground (USB transceiver)',
      type:  'GND',
      funcs: ['GND'],
      volt:  '0V',
      curr:  '—',
      note:  'Analog ground for the internal USB transceiver. Connect to the system ground plane, ideally with a short, direct path to reduce noise coupling into the USB signal path.',
      _rightSlot: 5,
    },
    {
      num:   21,
      id:    'TEST',
      lbl:   'TEST',
      name:  'Factory Test Pin',
      type:  'TEST',
      funcs: ['TEST'],
      volt:  '0V',
      curr:  '—',
      note:  'Factory test pin — must be tied to GND in all user designs. Connecting this pin to any other potential may cause the device to enter test mode and malfunction.',
      _rightSlot: 6,
    },
    {
      num:   22,
      id:    'EEDATA',
      lbl:   'EEDATA',
      name:  'EEPROM Data (93C46/56/66)',
      type:  'EE',
      funcs: ['EE'],
      volt:  '5V',
      curr:  '—',
      note:  'Bidirectional data line for the external 93C46, 93C56, or 93C66 serial EEPROM. The EEPROM stores USB descriptors (VID, PID, serial number, product string). If no EEPROM is connected, default FTDI descriptors are used.',
      _rightSlot: 7,
    },
    {
      num:   23,
      id:    'EECLK',
      lbl:   'EECLK',
      name:  'EEPROM Clock',
      type:  'EE',
      funcs: ['EE'],
      volt:  '5V',
      curr:  '—',
      note:  'Serial clock output for the external 93Cxx EEPROM. Driven by the FT232RL during EEPROM read and write cycles. Leave unconnected if no EEPROM is used.',
      _rightSlot: 8,
    },
    {
      num:   24,
      id:    'EECS',
      lbl:   'EECS',
      name:  'EEPROM Chip Select',
      type:  'EE',
      funcs: ['EE'],
      volt:  '5V',
      curr:  '—',
      note:  'Active-high chip select output for the external 93Cxx EEPROM. Asserted by the FT232RL when initiating an EEPROM access. Leave unconnected if no EEPROM is used.',
      _rightSlot: 9,
    },
    {
      num:   25,
      id:    'CLK6',
      lbl:   'CLKOUT',
      name:  'Clock Output (programmable)',
      type:  'CLK',
      funcs: ['CLK'],
      volt:  '3.3V / VCCIO',
      curr:  '±6 mA',
      note:  'Programmable clock output derived from the internal 12 MHz oscillator. Can be configured via the EEPROM to output 6 MHz, 3 MHz, 2 MHz, 1 MHz, 500 kHz, 250 kHz, 125 kHz, or 62.5 kHz. Useful as a clock source for external logic.',
      _rightSlot: 10,
    },
    {
      num:   26,
      id:    'DCD',
      lbl:   'DCD#',
      name:  'Data Carrier Detect (active low)',
      type:  'MODEM',
      funcs: ['MODEM'],
      volt:  '3.3V / 5V',
      curr:  '—',
      note:  'Modem status input, active low. Indicates that the modem has detected a carrier signal on the telephone line. Can also be used as a general-purpose input.',
      _rightSlot: 11,
    },
    {
      num:   27,
      id:    'DSR',
      lbl:   'DSR#',
      name:  'Data Set Ready (active low)',
      type:  'MODEM',
      funcs: ['MODEM'],
      volt:  '3.3V / 5V',
      curr:  '—',
      note:  'Modem status input, active low. Indicates that the modem or peripheral is ready to communicate. Part of DTR/DSR modem handshaking. Can also serve as a general-purpose input.',
      _rightSlot: 12,
    },
    {
      num:   28,
      id:    'CTS',
      lbl:   'CTS#',
      name:  'Clear To Send (active low)',
      type:  'MODEM',
      funcs: ['MODEM'],
      volt:  '3.3V / 5V',
      curr:  '—',
      note:  'Modem handshake input, active low. Indicates that the external device is ready to accept data from the FT232RL. Part of RTS/CTS hardware flow control.',
      _rightSlot: 13,
    },
  ],

  // ── ALTERNATE FUNCTIONS ───────────────────────────────────────
  altFuncs: {
    'TXD':    ['CBUS4 (configurable)'],
    'DTR':    ['CBUS (modem out)'],
    'RTS':    ['CBUS (modem out)'],
    'RXD':    ['CBUS4 (configurable)'],
    'RI':     ['CBUS (modem in)', 'GPIO'],
    'CLK6':   ['6 MHz', '3 MHz', '2 MHz', '1 MHz', '500 kHz', '250 kHz', '125 kHz', '62.5 kHz'],
    'DCD':    ['CBUS (modem in)', 'GPIO'],
    'DSR':    ['CBUS (modem in)', 'GPIO'],
    'CTS':    ['CBUS (modem in)', 'GPIO'],
    'EEDATA': ['Internal pull-up when EEPROM absent'],
  },

  // ── QUICK SPECS ───────────────────────────────────────────────
  quickSpecs: [
    { label: 'Interface',   value: 'USB 2.0 Full Speed',  color: '#4a9aee' },
    { label: 'Baud Rate',   value: '300 bps – 3 Mbps',    color: '#c8a850' },
    { label: 'Supply',      value: '4.0V – 5.25V',        color: '#78c878' },
    { label: 'I/O Voltage', value: '1.8V – 5.25V (VCCIO)',color: '#78c878' },
    { label: 'Oscillator',  value: 'Internal 12 MHz',     color: '#7090a8' },
    { label: 'EEPROM',      value: '93C46 / 56 / 66',     color: '#9898d8' },
    { label: 'Package',     value: 'SSOP-28',              color: '#e0e5ec' },
  ],

  // ── DETAILED SPECS ────────────────────────────────────────────
  dsSpecs: [
    { label: 'USB Speed',        value: 'Full Speed (12 Mbps)' },
    { label: 'UART Baud Range',  value: '300 bps to 3 Mbps' },
    { label: 'Data Bits',        value: '7 or 8' },
    { label: 'Stop Bits',        value: '1 or 2' },
    { label: 'Parity',           value: 'None, Odd, Even, Mark, Space' },
    { label: 'Flow Control',     value: 'RTS/CTS, DTR/DSR, XON/XOFF' },
    { label: 'VCC Supply',       value: '4.0V – 5.25V' },
    { label: 'VCCIO Range',      value: '1.8V – 5.25V' },
    { label: '3V3OUT Current',   value: '50 mA max' },
    { label: 'TX Buffer',        value: '256 bytes' },
    { label: 'RX Buffer',        value: '128 bytes' },
    { label: 'Oscillator',       value: 'Internal 12 MHz (no crystal needed)' },
    { label: 'EEPROM Interface', value: '93C46 / 93C56 / 93C66 (optional)' },
    { label: 'Clock Output',     value: '62.5 kHz – 6 MHz (8 steps)' },
    { label: 'Operating Temp',   value: '−40°C to +85°C (industrial)' },
    { label: 'Package',          value: 'SSOP-28' },
  ],

  // ── KEY FEATURES ──────────────────────────────────────────────
  dsFeatures: [
    'USB 2.0 Full Speed to asynchronous UART serial interface with no external crystal required',
    'Adjustable I/O voltage from 1.8V to 5.25V via VCCIO pin for easy multi-voltage interfacing',
    'Internal 256-byte TX and 128-byte RX FIFO buffers for efficient USB–UART data transfer',
    'Integrated 12 MHz oscillator eliminates the need for external clock components',
    'Optional external 93Cxx EEPROM for custom USB VID/PID, serial number, and product string',
    'Programmable CLKOUT pin provides clock output from 62.5 kHz to 6 MHz for external logic',
    'Full RS-232 modem handshaking signals: RTS, CTS, DTR, DSR, DCD, RI',
    'Hardware and software (XON/XOFF) flow control; supports 7 or 8 data bits, 1 or 2 stop bits',
    'Internal 3.3V LDO regulator output (3V3OUT) can supply up to 50 mA for external circuits',
    'FTDI royalty-free VCP and D2XX direct USB drivers available for all major operating systems',
    'TEST pin must be tied to GND; leaving it floating or high will cause malfunction',
  ],
};