// configs/mcp2515-config.js
// MCP2515 — Stand-Alone CAN Controller with SPI Interface
// Package: DIP-18  |  Manufacturer: Microchip Technology

window.IC_CONFIG = {

  // ── IDENTITY ──────────────────────────────────────────────────
  partName:     'MCP2515',
  partMPN:      'MCP2515-I/P',
  manufacturer: 'Microchip Technology',
  package:      'DIP-18',
  pinCount:     18,

  // ── LINKS ─────────────────────────────────────────────────────
  snapPageURL:  'https://www.snapeda.com/parts/MCP2515-I%2FP/Microchip%20Technology/view-part/',
  downloadURL:  'https://www.snapeda.com/parts/MCP2515-I%2FP/Microchip%20Technology/view-part/?ref=snapeda',
  datasheetURL: 'https://ww1.microchip.com/downloads/en/DeviceDoc/MCP2515-Stand-Alone-CAN-Controller-with-SPI-20001801J.pdf',

  // ── LAYOUT HINT ───────────────────────────────────────────────
  dipConfig: {
    pinsPerSide:  9,
    bodyX:        122, bodyY: 25, bodyW: 260, bodyH: 315,
    pinLength:    34,  pinWidthHalf: 16,
    notchSize:    8,   notchX: 14, notchY: 14,
    textSizes:    { mfr: 12, part: 22, pkg: 15, pinCount: 12 },
    labelSize:    11,  pinNumSize: 14, yOffset: -60
  },

  // ── CUSTOM PIN TYPES ──────────────────────────────────────────
  // MCP2515 mixes standard SPI/CAN/INT types with CAN-bus-specific
  // signals (TXCAN, RXCAN) and multi-function TX/RX request pins.
  customTypes: {
    CANTX: { c: '#f4a261', bg: 'rgba(244,162,97,.12)',  bd: 'rgba(244,162,97,.35)'  }, // CAN bus transmit line
    CANRX: { c: '#78c8f0', bg: 'rgba(120,200,240,.12)', bd: 'rgba(120,200,240,.35)' }, // CAN bus receive line
    TXRTS: { c: '#50c8a0', bg: 'rgba(80,200,160,.12)',  bd: 'rgba(80,200,160,.32)'  }, // TX Request-to-Send inputs
    RXBF:  { c: '#c078ff', bg: 'rgba(192,120,255,.11)', bd: 'rgba(192,120,255,.28)' }, // RX Buffer Full outputs
    OSC:   { c: '#7090a8', bg: 'rgba(112,144,168,.12)', bd: 'rgba(112,144,168,.30)' }, // Crystal / oscillator
  },

  // ── FILTER BUTTONS ────────────────────────────────────────────
  filterButtons: [
    { type: 'CANTX', label: 'TXCAN',          color: '#f4a261' },
    { type: 'CANRX', label: 'RXCAN',          color: '#78c8f0' },
    { type: 'SPI',   label: 'SPI',            color: '#4a9aee' },
    { type: 'INT',   label: 'Interrupt',      color: '#c8a850', fontSize:'10' },
    { type: 'TXRTS', label: 'TX RTS',         color: '#50c8a0' },
    { type: 'RXBF',  label: 'RX Buff Full', color: '#c078ff', fontSize:'7' },
    { type: 'OSC',   label: 'Oscillator',     color: '#7090a8', fontSize:'8' },
    { type: 'RESET', label: 'Reset',          color: '#ff9944' },
    { type: 'PWR',   label: 'VDD',            color: '#ff6b6b' },
    { type: 'GND',   label: 'VSS',            color: '#a8a8a8' },
  ],

  // ── PINS ──────────────────────────────────────────────────────
  // DIP-18: pins 1–9 on the left (top→bottom), pins 10–18 on the
  // right (_rightSlot 8=top-right down to 0=bottom-right).
  pins: [
    // ── LEFT SIDE (pins 1–9) ─────────────────────────────────────
    { num:  1, id: 'TXCAN',  lbl: 'TXCAN',  name: 'CAN Bus Transmit Output',
      type: 'CANTX', funcs: ['CANTX'],
      volt: '5V', curr: 'N/A',
      note: 'CAN bus transmit output. Connect to the TXD pin of a CAN bus transceiver (e.g. MCP2551). Outputs the encoded CAN bit stream generated by the MCP2515 controller.' },

    { num:  2, id: 'RXCAN',  lbl: 'RXCAN',  name: 'CAN Bus Receive Input',
      type: 'CANRX', funcs: ['CANRX'],
      volt: '5V', curr: 'N/A',
      note: 'CAN bus receive input. Connect to the RXD pin of a CAN bus transceiver. The MCP2515 samples this line to decode incoming CAN frames.' },

    { num:  3, id: 'CLKOUT', lbl: 'CLKOUT', name: 'Clock Output / SOF Signal',
      type: 'OSC',   funcs: ['OSC'],
      volt: '5V', curr: 'N/A',
      note: 'Programmable clock output pin. Can output a prescaled version of the oscillator clock (FOSC/1, /2, /4, or /8) for use as a clock source by other devices. Alternatively configurable as a Start-Of-Frame (SOF) signal output.' },

    { num:  4, id: 'TX0RTS', lbl: 'TX0RTS', name: 'TX Buffer 0 Request-to-Send',
      type: 'TXRTS', funcs: ['TXRTS'],
      volt: '5V', curr: 'N/A',
      note: 'TX Buffer 0 Request-to-Send input (active low). When pulled low, requests immediate transmission of the message loaded in TX Buffer 0. Can also be configured as a general-purpose digital input via register TXRTSCTRL.' },

    { num:  5, id: 'TX1RTS', lbl: 'TX1RTS', name: 'TX Buffer 1 Request-to-Send',
      type: 'TXRTS', funcs: ['TXRTS'],
      volt: '5V', curr: 'N/A',
      note: 'TX Buffer 1 Request-to-Send input (active low). When pulled low, requests immediate transmission of the message loaded in TX Buffer 1. Can also be configured as a general-purpose digital input.' },

    { num:  6, id: 'TX2RTS', lbl: 'TX2RTS', name: 'TX Buffer 2 Request-to-Send',
      type: 'TXRTS', funcs: ['TXRTS'],
      volt: '5V', curr: 'N/A',
      note: 'TX Buffer 2 Request-to-Send input (active low). When pulled low, requests immediate transmission of the message loaded in TX Buffer 2. Can also be configured as a general-purpose digital input.' },

    { num:  7, id: 'OSC1',   lbl: 'OSC1',   name: 'Oscillator Input',
      type: 'OSC',   funcs: ['OSC'],
      volt: '5V', curr: 'N/A',
      note: 'Oscillator crystal input. Connect one leg of a crystal (or ceramic resonator) here. An external clock source can also be applied directly to this pin if no crystal is used.' },

    { num:  8, id: 'OSC2',   lbl: 'OSC2',   name: 'Oscillator Output',
      type: 'OSC',   funcs: ['OSC'],
      volt: '5V', curr: 'N/A',
      note: 'Oscillator crystal output. Connect the other leg of the crystal or ceramic resonator here. Leave unconnected if using an external clock source on OSC1.' },

    { num:  9, id: 'VSS',    lbl: 'VSS',    name: 'Ground',
      type: 'GND',   funcs: ['GND'],
      volt: '0V', curr: 'N/A',
      note: 'Ground reference. Connect to the system ground plane. Decouple VDD to VSS with a 100 nF ceramic capacitor placed as close to the device as possible.' },

    // ── RIGHT SIDE (pins 10–18) ───────────────────────────────────
    { num: 10, id: 'VDD',    lbl: 'VDD',    name: 'Supply Voltage',
      type: 'PWR',   funcs: ['PWR'],
      volt: '2.7–5.5V', curr: 'N/A',
      note: 'Positive supply voltage. The MCP2515 operates from 2.7V to 5.5V. Decouple with a 100 nF ceramic capacitor and a 10 µF bulk capacitor placed close to VDD and VSS.',
      _rightSlot: 8 },

    { num: 11, id: 'CS',     lbl: '/CS',    name: 'SPI Chip Select (Active Low)',
      type: 'SPI',   funcs: ['SPI'],
      volt: '5V', curr: 'N/A',
      note: 'SPI chip select input (active low). Drive low to enable communication with the MCP2515. Must be held low for the entire duration of an SPI transaction. Tie high when bus is idle.',
      _rightSlot: 7 },

    { num: 12, id: 'SO',     lbl: 'SO',     name: 'SPI Data Output (MISO)',
      type: 'SPI',   funcs: ['SPI'],
      volt: '5V', curr: 'N/A',
      note: 'SPI serial data output (Master-In Slave-Out). Data is shifted out on the falling edge of SCK. Goes high-impedance when /CS is deasserted.',
      _rightSlot: 6 },

    { num: 13, id: 'SI',     lbl: 'SI',     name: 'SPI Data Input (MOSI)',
      type: 'SPI',   funcs: ['SPI'],
      volt: '5V', curr: 'N/A',
      note: 'SPI serial data input (Master-Out Slave-In). Data is clocked in on the rising edge of SCK. Supports SPI Mode 0,0 and Mode 1,1.',
      _rightSlot: 5 },

    { num: 14, id: 'SCK',    lbl: 'SCK',    name: 'SPI Clock Input',
      type: 'SPI',   funcs: ['SPI'],
      volt: '5V', curr: 'N/A',
      note: 'SPI clock input. Maximum clock frequency is 10 MHz. The MCP2515 supports SPI modes 0,0 (CPOL=0, CPHA=0) and 1,1 (CPOL=1, CPHA=1).',
      _rightSlot: 4 },

    { num: 15, id: 'INT',    lbl: '/INT',   name: 'Interrupt Output (Active Low)',
      type: 'INT',   funcs: ['INT'],
      volt: '5V', curr: 'N/A',
      note: 'Interrupt output (active low, open-drain). Asserted when any enabled interrupt condition occurs, including message reception, transmission complete, error states, or wakeup. Connect to a host MCU interrupt input with an external pull-up resistor.',
      _rightSlot: 3 },

    { num: 16, id: 'RX1BF',  lbl: 'RX1BF',  name: 'RX Buffer 1 Full / GP Output',
      type: 'RXBF',  funcs: ['RXBF'],
      volt: '5V', curr: 'N/A',
      note: 'RX Buffer 1 Full output (active low). Asserted when a valid message has been loaded into RX Buffer 1. Can also be configured as a general-purpose digital output via register BFPCTRL.',
      _rightSlot: 2 },

    { num: 17, id: 'RX0BF',  lbl: 'RX0BF',  name: 'RX Buffer 0 Full / GP Output',
      type: 'RXBF',  funcs: ['RXBF'],
      volt: '5V', curr: 'N/A',
      note: 'RX Buffer 0 Full output (active low). Asserted when a valid message has been loaded into RX Buffer 0. Can also be configured as a general-purpose digital output or disabled entirely via register BFPCTRL.',
      _rightSlot: 1 },

    { num: 18, id: 'RESET',  lbl: '/RST',   name: 'Reset Input (Active Low)',
      type: 'RESET', funcs: ['RESET'],
      volt: '5V', curr: 'N/A',
      note: 'Active-low hardware reset input. Drive low to reset all internal registers to their default state. A software reset can also be issued via the SPI RESET instruction (0xC0) without asserting this pin. Connect to VDD through a pull-up resistor if not driven.',
      _rightSlot: 0 },
  ],

  // ── ALTERNATE FUNCTIONS ───────────────────────────────────────
  altFuncs: {
    'CLKOUT': ['SOF (Start-Of-Frame) output'],
    'TX0RTS': ['GP digital input (via TXRTSCTRL)'],
    'TX1RTS': ['GP digital input (via TXRTSCTRL)'],
    'TX2RTS': ['GP digital input (via TXRTSCTRL)'],
    'RX0BF':  ['GP digital output (via BFPCTRL)', 'Disabled'],
    'RX1BF':  ['GP digital output (via BFPCTRL)', 'Disabled'],
    'OSC1':   ['External clock input'],
  },

  // ── QUICK SPECS ───────────────────────────────────────────────
  quickSpecs: [
    { label: 'Protocol',    value: 'CAN 2.0B (Active)',       color: '#f4a261' },
    { label: 'Interface',   value: 'SPI (10 MHz max)',         color: '#4a9aee' },
    { label: 'Supply',      value: '2.7–5.5V',                color: '#78c878' },
    { label: 'TX Buffers',  value: '3 (with priority ctrl)',  color: '#50c8a0' },
    { label: 'RX Buffers',  value: '2 (with 6 filters)',      color: '#78c8f0' },
    { label: 'CAN Speed',   value: 'Up to 1 Mb/s',            color: '#c8a850' },
  ],

  // ── DETAILED SPECS ────────────────────────────────────────────
  dsSpecs: [
    { label: 'CAN Standard',    value: 'CAN 2.0B Active (11-bit and 29-bit IDs)' },
    { label: 'Data Rate',       value: 'Up to 1 Mb/s' },
    { label: 'TX Buffers',      value: '3 buffers with programmable priority' },
    { label: 'RX Buffers',      value: '2 buffers with 6 acceptance filters and 2 masks' },
    { label: 'SPI Speed',       value: '10 MHz maximum' },
    { label: 'SPI Modes',       value: '0,0 (CPOL=0, CPHA=0) and 1,1 (CPOL=1, CPHA=1)' },
    { label: 'Supply Voltage',  value: '2.7V to 5.5V' },
    { label: 'Supply Current',  value: '5 mA typical active, 1 µA sleep' },
    { label: 'Sleep / Wakeup',  value: 'Yes — wakeup via CAN bus activity' },
    { label: 'Error Handling',  value: 'Full CAN error detection, fault confinement' },
    { label: 'Package Options', value: 'DIP-18, SOIC-18, TSSOP-20, QFN-20' },
    { label: 'Temperature',     value: '-40°C to +85°C (Industrial)' },
  ],

  // ── KEY FEATURES ─────────────────────────────────────────────
  dsFeatures: [
    'Implements CAN 2.0B specification — supports both standard (11-bit) and extended (29-bit) identifiers',
    'Three transmit buffers with individually programmable priority and abort capability',
    'Two receive buffers with six acceptance filters and two masks to reduce host MCU interrupt load',
    'SPI interface runs up to 10 MHz, compatible with modes 0,0 and 1,1',
    'TX0RTS, TX1RTS, TX2RTS pins provide hardware Request-to-Send without SPI overhead',
    'RX0BF and RX1BF pins signal buffer full state without polling over SPI',
    'CLKOUT pin can provide a prescaled system clock or SOF signal to other devices',
    'Programmable wake-up filter rejects short glitches to prevent spurious wakeup from sleep mode',
    'Full CAN error detection including CRC, bit stuffing, frame format, and acknowledgement errors',
    'Fault confinement state machine: Error Active → Error Passive → Bus-Off with auto-recovery option',
    'One-shot transmission mode prevents automatic retransmission for time-critical systems',
    'Listen-Only mode allows silent bus monitoring and baud-rate detection without affecting the bus',
  ],
};