// configs/pca9685-config.js
// NXP PCA9685 — 16-Channel, 12-bit PWM Fm+ I²C-Bus LED Controller
// Package: TSSOP-28 (rendered as DIP-28)
// Pin mapping verified against user-provided pinout table

window.IC_CONFIG = {

  // ── IDENTITY ──────────────────────────────────────────────────
  partName:     'PCA9685',
  partMPN:      'PCA9685PW',
  manufacturer: 'NXP',
  package:      'DIP-28',
  pinCount:     28,

  // ── LINKS ─────────────────────────────────────────────────────
  snapPageURL:  'https://www.snapeda.com/parts/PCA9685PW/NXP/view-part/',
  downloadURL:  'https://www.snapeda.com/parts/PCA9685PW/NXP/view-part/?ref=snapeda',
  datasheetURL: 'https://www.nxp.com/docs/en/data-sheet/PCA9685.pdf',

  // ── LAYOUT HINT (DIP-28) ──────────────────────────────────────
  dipConfig: {
    pinsPerSide:  14,
    bodyX:        122, bodyY: 25, bodyW: 260, bodyH: 490,
    pinLength:    34,  pinWidthHalf: 16,
    notchSize:    8,   notchX: 14, notchY: 14,
    textSizes:    { mfr: 14, part: 22, pkg: 14, pinCount: 12 },
    labelSize:    11,  pinNumSize: 14, yOffset: -40,
  },

  // ── CUSTOM TYPES ──────────────────────────────────────────────
  // PCA9685 has address bits, an output-enable, and an external clock
  // pin that are not in the standard palette
  customTypes: {
    ADDR: { c: '#50c8a0', bg: 'rgba(80,200,160,.12)',  bd: 'rgba(80,200,160,.32)' },
    OE:   { c: '#ff9944', bg: 'rgba(255,153,68,.12)',  bd: 'rgba(255,153,68,.30)' },
    CLK:  { c: '#7090a8', bg: 'rgba(112,144,168,.12)', bd: 'rgba(112,144,168,.35)' },
  },

  // ── FILTER BUTTONS ────────────────────────────────────────────
  filterButtons: [
    { type: 'PWM',  label: 'PWM  (LED0–15)', color: '#50c8c8', FontSize:'10px' },
    { type: 'I2C',  label: 'I²C(SDA/SCL)', color: '#9898d8',FontSize:'11px' },
    { type: 'ADDR', label: 'Addr(A0–A5)', color: '#50c8a0',FontSize:'11px' },
    { type: 'OE',   label: 'Out En', color: '#ff9944' },
    { type: 'CLK',  label: 'Ext Clk', color: '#7090a8' },
    { type: 'PWR',  label: 'Power(VDD)', color: '#ff6b6b',FontSize:'12px' },
    { type: 'GND',  label: 'GND(VSS)', color: '#a8a8a8', FontSize:'11px' },
  ],

  // ── PINS ──────────────────────────────────────────────────────
  // Left side:  pins 1–14  (top → bottom, no _rightSlot)
  // Right side: pins 15–28 (_rightSlot 0=top-right … 13=bottom-right)
  pins: [

    // ── LEFT SIDE (pins 1–14) ─────────────────────────────────
    {
      num:   1,
      id:    'A0',
      lbl:   'A0',
      name:  'Hardware Address Bit 0',
      type:  'ADDR',
      funcs: ['ADDR'],
      volt:  '0V or VDD',
      curr:  '—',
      note:  'I²C hardware address bit 0. Pull to VDD or GND to set the LSB of the 6-bit programmable I²C address. Up to 62 devices can share the same bus by using different A0–A5 combinations.',
    },
    {
      num:   2,
      id:    'A1',
      lbl:   'A1',
      name:  'Hardware Address Bit 1',
      type:  'ADDR',
      funcs: ['ADDR'],
      volt:  '0V or VDD',
      curr:  '—',
      note:  'I²C hardware address bit 1. Pull to VDD or GND to set bit 1 of the 6-bit programmable I²C address. Combine with A0, A2–A5 to form a unique bus address.',
    },
    {
      num:   3,
      id:    'A2',
      lbl:   'A2',
      name:  'Hardware Address Bit 2',
      type:  'ADDR',
      funcs: ['ADDR'],
      volt:  '0V or VDD',
      curr:  '—',
      note:  'I²C hardware address bit 2. Pull to VDD or GND to set bit 2 of the 6-bit programmable I²C address.',
    },
    {
      num:   4,
      id:    'A3',
      lbl:   'A3',
      name:  'Hardware Address Bit 3',
      type:  'ADDR',
      funcs: ['ADDR'],
      volt:  '0V or VDD',
      curr:  '—',
      note:  'I²C hardware address bit 3. Pull to VDD or GND to set bit 3 of the 6-bit programmable I²C address.',
    },
    {
      num:   5,
      id:    'A4',
      lbl:   'A4',
      name:  'Hardware Address Bit 4',
      type:  'ADDR',
      funcs: ['ADDR'],
      volt:  '0V or VDD',
      curr:  '—',
      note:  'I²C hardware address bit 4. Pull to VDD or GND to set bit 4 of the 6-bit programmable I²C address.',
    },
    {
      num:   6,
      id:    'LED0',
      lbl:   'LED0',
      name:  'PWM Channel 0 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 0 open-drain output. 12-bit resolution (0–4095) controls the on/off time within each PWM period. Output is active (low) when OE# is driven low. Can drive LEDs directly or control servo signals.',
    },
    {
      num:   7,
      id:    'LED1',
      lbl:   'LED1',
      name:  'PWM Channel 1 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 1 open-drain output. 12-bit resolution gives 4096 steps of duty-cycle control per channel. Each channel has independent on-time and off-time registers.',
    },
    {
      num:   8,
      id:    'LED2',
      lbl:   'LED2',
      name:  'PWM Channel 2 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 2 open-drain output. Independently controlled via I²C registers LED2_ON_L, LED2_ON_H, LED2_OFF_L, LED2_OFF_H.',
    },
    {
      num:   9,
      id:    'LED3',
      lbl:   'LED3',
      name:  'PWM Channel 3 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 3 open-drain output. Independently controlled via I²C registers LED3_ON_L, LED3_ON_H, LED3_OFF_L, LED3_OFF_H.',
    },
    {
      num:   10,
      id:    'LED4',
      lbl:   'LED4',
      name:  'PWM Channel 4 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 4 open-drain output. Independently controlled via I²C registers LED4_ON_L, LED4_ON_H, LED4_OFF_L, LED4_OFF_H.',
    },
    {
      num:   11,
      id:    'LED5',
      lbl:   'LED5',
      name:  'PWM Channel 5 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 5 open-drain output. Independently controlled via I²C registers LED5_ON_L, LED5_ON_H, LED5_OFF_L, LED5_OFF_H.',
    },
    {
      num:   12,
      id:    'LED6',
      lbl:   'LED6',
      name:  'PWM Channel 6 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 6 open-drain output. Independently controlled via I²C registers LED6_ON_L, LED6_ON_H, LED6_OFF_L, LED6_OFF_H.',
    },
    {
      num:   13,
      id:    'LED7',
      lbl:   'LED7',
      name:  'PWM Channel 7 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 7 open-drain output. Independently controlled via I²C registers LED7_ON_L, LED7_ON_H, LED7_OFF_L, LED7_OFF_H.',
    },
    {
      num:   14,
      id:    'VSS',
      lbl:   'VSS',
      name:  'Ground (0V)',
      type:  'GND',
      funcs: ['GND'],
      volt:  '0V',
      curr:  '—',
      note:  'Device ground supply. Connect to the system ground plane. Place a 100 nF decoupling capacitor between VDD (pin 28) and VSS (pin 14) as close to the IC as possible.',
    },

    // ── RIGHT SIDE (pins 15–28) ───────────────────────────────
    {
      num:   15,
      id:    'LED8',
      lbl:   'LED8',
      name:  'PWM Channel 8 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 8 open-drain output. Independently controlled via I²C registers LED8_ON_L, LED8_ON_H, LED8_OFF_L, LED8_OFF_H.',
      _rightSlot: 0,
    },
    {
      num:   16,
      id:    'LED9',
      lbl:   'LED9',
      name:  'PWM Channel 9 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 9 open-drain output. Independently controlled via I²C registers LED9_ON_L, LED9_ON_H, LED9_OFF_L, LED9_OFF_H.',
      _rightSlot: 1,
    },
    {
      num:   17,
      id:    'LED10',
      lbl:   'LED10',
      name:  'PWM Channel 10 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 10 open-drain output. Independently controlled via I²C registers LED10_ON_L, LED10_ON_H, LED10_OFF_L, LED10_OFF_H.',
      _rightSlot: 2,
    },
    {
      num:   18,
      id:    'LED11',
      lbl:   'LED11',
      name:  'PWM Channel 11 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 11 open-drain output. Independently controlled via I²C registers LED11_ON_L, LED11_ON_H, LED11_OFF_L, LED11_OFF_H.',
      _rightSlot: 3,
    },
    {
      num:   19,
      id:    'LED12',
      lbl:   'LED12',
      name:  'PWM Channel 12 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 12 open-drain output. Independently controlled via I²C registers LED12_ON_L, LED12_ON_H, LED12_OFF_L, LED12_OFF_H.',
      _rightSlot: 4,
    },
    {
      num:   20,
      id:    'LED13',
      lbl:   'LED13',
      name:  'PWM Channel 13 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 13 open-drain output. Independently controlled via I²C registers LED13_ON_L, LED13_ON_H, LED13_OFF_L, LED13_OFF_H.',
      _rightSlot: 5,
    },
    {
      num:   21,
      id:    'LED14',
      lbl:   'LED14',
      name:  'PWM Channel 14 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 14 open-drain output. Independently controlled via I²C registers LED14_ON_L, LED14_ON_H, LED14_OFF_L, LED14_OFF_H.',
      _rightSlot: 6,
    },
    {
      num:   22,
      id:    'LED15',
      lbl:   'LED15',
      name:  'PWM Channel 15 Output',
      type:  'PWM',
      funcs: ['PWM'],
      volt:  '0V – VDD',
      curr:  '10 mA (25 mA max)',
      note:  'PWM channel 15 open-drain output. Independently controlled via I²C registers LED15_ON_L, LED15_ON_H, LED15_OFF_L, LED15_OFF_H.',
      _rightSlot: 7,
    },
    {
      num:   23,
      id:    'OE',
      lbl:   'OE#',
      name:  'Output Enable — Active Low',
      type:  'OE',
      funcs: ['OE'],
      volt:  '0V or VDD',
      curr:  '—',
      note:  'Output enable input, active low. When driven low all 16 PWM outputs are enabled. When driven high all outputs are driven to the state defined by the OUTNE bits in MODE2 register (default: high-impedance). Pull to GND for always-on operation, or drive from a GPIO for software control.',
      _rightSlot: 8,
    },
    {
      num:   24,
      id:    'A5',
      lbl:   'A5',
      name:  'Hardware Address Bit 5',
      type:  'ADDR',
      funcs: ['ADDR'],
      volt:  '0V or VDD',
      curr:  '—',
      note:  'I²C hardware address bit 5 (MSB of the 6-bit address field). Pull to VDD or GND. Together with A0–A4 this allows up to 62 unique I²C addresses (0x40–0x7E, excluding the All Call address 0x70).',
      _rightSlot: 9,
    },
    {
      num:   25,
      id:    'EXTCLK',
      lbl:   'EXTCLK',
      name:  'External Clock Input',
      type:  'CLK',
      funcs: ['CLK'],
      volt:  '0V – VDD',
      curr:  '—',
      note:  'External clock input. When the EXTCLK bit in MODE1 register is set, this pin accepts an external clock source (1 Hz to 50 MHz) instead of the internal 25 MHz oscillator. To enable: write SLEEP bit, then set EXTCLK bit — this is a one-time latch until power cycle. Leave unconnected when using the internal oscillator.',
      _rightSlot: 10,
    },
    {
      num:   26,
      id:    'SCL',
      lbl:   'SCL',
      name:  'I²C Serial Clock Line',
      type:  'I2C',
      funcs: ['I2C'],
      volt:  '0V – VDD',
      curr:  '—',
      note:  'I²C serial clock input. Supports Standard-mode (100 kHz), Fast-mode (400 kHz), and Fast-mode Plus (Fm+, 1 MHz) I²C speeds. Requires an external pull-up resistor to VDD (typical 4.7 kΩ for Fast-mode, 1 kΩ for Fm+).',
      _rightSlot: 11,
    },
    {
      num:   27,
      id:    'SDA',
      lbl:   'SDA',
      name:  'I²C Serial Data Line',
      type:  'I2C',
      funcs: ['I2C'],
      volt:  '0V – VDD',
      curr:  '—',
      note:  'I²C serial data bidirectional line. Used for both address and data transfer. Supports Standard-mode, Fast-mode, and Fast-mode Plus. Requires an external pull-up resistor to VDD (typical 4.7 kΩ for Fast-mode, 1 kΩ for Fm+).',
      _rightSlot: 12,
    },
    {
      num:   28,
      id:    'VDD',
      lbl:   'VDD',
      name:  'Supply Voltage',
      type:  'PWR',
      funcs: ['PWR'],
      volt:  '2.3V – 5.5V',
      curr:  '—',
      note:  'Main device supply voltage. Operating range is 2.3V to 5.5V. Decouple with a 100 nF ceramic capacitor between VDD (pin 28) and VSS (pin 14), placed as close to the IC pins as possible to suppress switching noise from PWM outputs.',
      _rightSlot: 13,
    },
  ],

  // ── ALTERNATE FUNCTIONS ───────────────────────────────────────
  altFuncs: {
    'LED0':  ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED1':  ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED2':  ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED3':  ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED4':  ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED5':  ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED6':  ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED7':  ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED8':  ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED9':  ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED10': ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED11': ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED12': ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED13': ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED14': ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'LED15': ['GPIO output (full ON/OFF via bit 4 of LEDn_ON_H / LEDn_OFF_H)'],
    'EXTCLK': ['Internal 25 MHz oscillator (default, when EXTCLK bit = 0)'],
  },

  // ── QUICK SPECS ───────────────────────────────────────────────
  quickSpecs: [
    { label: 'Channels',    value: '16 PWM outputs',        color: '#50c8c8' },
    { label: 'Resolution',  value: '12-bit (4096 steps)',   color: '#c8a850' },
    { label: 'PWM Freq',    value: '24 Hz – 1526 Hz',       color: '#50c8c8' },
    { label: 'Interface',   value: 'I²C Fm+ (up to 1 MHz)', color: '#9898d8' },
    { label: 'Supply',      value: '2.3V – 5.5V',           color: '#78c878' },
    { label: 'I²C Address', value: '62 selectable (A0–A5)', color: '#50c8a0' },
    { label: 'Package',     value: 'TSSOP-28',               color: '#e0e5ec' },
  ],

  // ── DETAILED SPECS ────────────────────────────────────────────
  dsSpecs: [
    { label: 'PWM Channels',     value: '16 independent open-drain outputs' },
    { label: 'PWM Resolution',   value: '12-bit (0–4095 counts)' },
    { label: 'PWM Frequency',    value: '24 Hz to 1526 Hz (set via PRE_SCALE register)' },
    { label: 'I²C Speed',        value: 'Standard (100 kHz), Fast (400 kHz), Fm+ (1 MHz)' },
    { label: 'I²C Addresses',    value: '62 programmable (0x40–0x7E) + All Call (0x70)' },
    { label: 'Supply Voltage',   value: '2.3V to 5.5V' },
    { label: 'Output Current',   value: '10 mA typical, 25 mA max per channel' },
    { label: 'Internal Osc',     value: '25 MHz (±5%)' },
    { label: 'External Clock',   value: '1 Hz to 50 MHz via EXTCLK pin' },
    { label: 'Operating Temp',   value: '−40°C to +85°C' },
    { label: 'Package',          value: 'TSSOP-28' },
  ],

  // ── KEY FEATURES ──────────────────────────────────────────────
  dsFeatures: [
    '16 individually controllable PWM output channels, each with 12-bit (4096-step) duty-cycle resolution',
    'Programmable PWM frequency from 24 Hz to 1526 Hz via the PRE_SCALE register — ideal for servos and LED dimming',
    'I²C Fast-mode Plus (Fm+) support up to 1 MHz; up to 62 devices on the same bus using A0–A5 address pins',
    'Internal 25 MHz oscillator; optional external clock via EXTCLK pin (1 Hz to 50 MHz)',
    'Open-drain PWM outputs rated at 25 mA max per channel — can directly drive LEDs with series resistors',
    'Each output can be set to full ON or full OFF (GPIO mode) by setting bit 4 in the LEDn_ON_H or LEDn_OFF_H register',
    'OE# pin allows all outputs to be simultaneously enabled or disabled without I²C communication',
    'Software Reset via I²C General Call address (0x00) + 0x06 byte — resets all registers to power-on defaults',
    'Low-power sleep mode: set SLEEP bit in MODE1 register to stop the oscillator and reduce current draw',
    'Cascadable: multiple PCA9685 devices share SDA/SCL with independent I²C addresses for up to 992 PWM channels',
  ],
};