window.IC_CONFIG = {
  name: "DM7486N",
  manufacturer: "Texas Instruments",
  package: "DIP-14",
  type: "Digital IC",
  description: "Quad 2-input XOR gate. Each gate performs the logic function Y = A ⊕ B.",
  datasheet: "https://www.ti.com/lit/ds/symlink/sn74ls86.pdf",
  pinCount: 14,
  dipConfig: {
    rows: 2,
    pinsPerRow: 7,
    pinPitch: 2.54,
  },
  pins: [
    { number: 1, label: "1A", type: "Input", function: "Gate 1 input A" },
    { number: 2, label: "1B", type: "Input", function: "Gate 1 input B" },
    { number: 3, label: "1Y", type: "Output", function: "Gate 1 output" },
    { number: 4, label: "2A", type: "Input", function: "Gate 2 input A" },
    { number: 5, label: "2B", type: "Input", function: "Gate 2 input B" },
    { number: 6, label: "2Y", type: "Output", function: "Gate 2 output" },
    { number: 7, label: "GND", type: "Power", function: "Ground" },
    { number: 8, label: "3Y", type: "Output", function: "Gate 3 output" },
    { number: 9, label: "3A", type: "Input", function: "Gate 3 input A" },
    { number: 10, label: "3B", type: "Input", function: "Gate 3 input B" },
    { number: 11, label: "4Y", type: "Output", function: "Gate 4 output" },
    { number: 12, label: "4A", type: "Input", function: "Gate 4 input A" },
    { number: 13, label: "4B", type: "Input", function: "Gate 4 input B" },
    { number: 14, label: "VCC", type: "Power", function: "Supply voltage (5V)" },
  ],
  quickSpecs: {
    logicFamily: "TTL",
    voltageRange: "4.75V–5.25V",
    propagationDelay: "10ns typical",
    inputType: "Digital",
    outputType: "Digital",
  },
  keyFeatures: [
    "Quad 2-input XOR gates",
    "Standard TTL logic levels",
    "High-speed switching",
    "Compatible with 74LS series",
  ],
};
