window.IC_CONFIG = {

  // ── IDENTITY ──────────────────────────────────────────────────
  partName:     'ATmega32',
  partMPN:      'ATMEGA32-16PU',
  manufacturer: 'Atmel',
  package:      'TQFP-44',
  pinCount:     44,

  // ── LINKS ─────────────────────────────────────────────────────
  snapPageURL:  'https://www.snapeda.com/parts/ATMEGA32-16PU/Microchip/view-part/',
  downloadURL:  'https://www.snapeda.com/parts/ATMEGA32-16PU/Microchip/view-part/?ref=snapeda',
  datasheetURL: 'https://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-8155-8-bit-AVR-ATmega16A_Datasheet.pdf',

  // ── LAYOUT HINT (QFP/TQFP) ───────────────────────────────────
  // 44 pins / 4 sides = 11 pins per side
  qfpConfig: {
    pinsPerSide: 11,
    bodySize:    340,
    pinLength:   34,
    pinWidth:    15,
    pinGap:      2,
  },

  // ── PINS ──────────────────────────────────────────────────────
  // QFP counter-clockwise from pin 1:
  //   Pins  1–11  → LEFT   side, top → bottom
  //   Pins 12–22  → BOTTOM side, left → right
  //   Pins 23–33  → RIGHT  side, bottom → top
  //   Pins 34–44  → TOP    side, right → left
  pins: [
    // ── LEFT (1–11) ───────────────────────────────────────────
    {
      num:  1,  id: 'PB0',   lbl: 'PB0',
      name: 'PB0 / XCK / T0',
      type: 'GPIO',  funcs: ['GPIO', 'TIMER'],
      volt: '5V', curr: '40mA',
      note: 'Port B bit 0. External clock input for USART (XCK). External clock input for Timer/Counter0 (T0).',
    },
    {
      num:  2,  id: 'PB1',   lbl: 'PB1',
      name: 'PB1 / T1',
      type: 'TIMER', funcs: ['GPIO', 'TIMER'],
      volt: '5V', curr: '40mA',
      note: 'Port B bit 1. Timer/Counter1 external clock input (T1).',
    },
    {
      num:  3,  id: 'PB2',   lbl: 'PB2',
      name: 'PB2 / AIN0 / INT2',
      type: 'INT',   funcs: ['GPIO', 'ADC', 'INT'],
      volt: '5V', curr: '40mA',
      note: 'Port B bit 2. Analog Comparator positive input (AIN0). External Interrupt 2 (INT2).',
    },
    {
      num:  4,  id: 'PB3',   lbl: 'PB3',
      name: 'PB3 / AIN1 / OC0',
      type: 'PWM',   funcs: ['GPIO', 'ADC', 'PWM'],
      volt: '5V', curr: '40mA',
      note: 'Port B bit 3. Analog Comparator negative input (AIN1). Timer/Counter0 Output Compare (OC0) — PWM output.',
    },
    {
      num:  5,  id: 'PB4',   lbl: 'PB4',
      name: 'PB4 / SS',
      type: 'SPI',   funcs: ['GPIO', 'SPI'],
      volt: '5V', curr: '40mA',
      note: 'Port B bit 4. SPI Slave Select input (active LOW). Must be held high or configured as output in master mode.',
    },
    {
      num:  6,  id: 'PB5',   lbl: 'PB5',
      name: 'PB5 / MOSI',
      type: 'SPI',   funcs: ['GPIO', 'SPI'],
      volt: '5V', curr: '40mA',
      note: 'Port B bit 5. SPI Master Out / Slave In data line. Also used for ISP programming.',
    },
    {
      num:  7,  id: 'PB6',   lbl: 'PB6',
      name: 'PB6 / MISO',
      type: 'SPI',   funcs: ['GPIO', 'SPI'],
      volt: '5V', curr: '40mA',
      note: 'Port B bit 6. SPI Master In / Slave Out data line. Also used for ISP programming.',
    },
    {
      num:  8,  id: 'PB7',   lbl: 'PB7',
      name: 'PB7 / SCK',
      type: 'SPI',   funcs: ['GPIO', 'SPI'],
      volt: '5V', curr: '40mA',
      note: 'Port B bit 7. SPI Serial Clock. Also used for ISP programming.',
    },
    {
      num:  9,  id: 'RESET', lbl: 'RST',
      name: 'RESET',
      type: 'RESET', funcs: ['RESET'],
      volt: '5V', curr: 'N/A',
      note: 'External reset input. Active LOW. Internal pull-up resistor enabled. Pulling LOW for >1.5µs generates a reset.',
    },
    {
      num: 10,  id: 'VCC1',  lbl: 'VCC',
      name: 'VCC',
      type: 'PWR',   funcs: ['PWR'],
      volt: '5V', curr: '200mA',
      note: 'Digital power supply (2.7V–5.5V). Decouple with 100nF ceramic capacitor close to pin.',
    },
    {
      num: 11,  id: 'GND1',  lbl: 'GND',
      name: 'GND',
      type: 'GND',   funcs: ['GND'],
      volt: '0V', curr: 'N/A',
      note: 'Ground. Connect to system ground plane.',
    },

    // ── BOTTOM (12–22) ────────────────────────────────────────
    {
      num: 12,  id: 'XTAL1', lbl: 'XT1',
      name: 'XTAL1',
      type: 'XTAL',  funcs: ['XTAL'],
      volt: '5V', curr: 'N/A',
      note: 'Crystal oscillator input. Connect one leg of crystal here. Also accepts external clock signal directly.',
    },
    {
      num: 13,  id: 'XTAL2', lbl: 'XT2',
      name: 'XTAL2',
      type: 'XTAL',  funcs: ['XTAL'],
      volt: '5V', curr: 'N/A',
      note: 'Crystal oscillator output. Connect other leg of crystal here. Leave floating when using external clock on XTAL1.',
    },
    {
      num: 14,  id: 'PD0',   lbl: 'PD0',
      name: 'PD0 / RXD',
      type: 'USART', funcs: ['GPIO', 'USART'],
      volt: '5V', curr: '40mA',
      note: 'Port D bit 0. USART Receive Data input (RXD).',
    },
    {
      num: 15,  id: 'PD1',   lbl: 'PD1',
      name: 'PD1 / TXD',
      type: 'USART', funcs: ['GPIO', 'USART'],
      volt: '5V', curr: '40mA',
      note: 'Port D bit 1. USART Transmit Data output (TXD).',
    },
    {
      num: 16,  id: 'PD2',   lbl: 'PD2',
      name: 'PD2 / INT0',
      type: 'INT',   funcs: ['GPIO', 'INT'],
      volt: '5V', curr: '40mA',
      note: 'Port D bit 2. External Interrupt 0 (INT0). Configurable as rising edge, falling edge, or low-level trigger.',
    },
    {
      num: 17,  id: 'PD3',   lbl: 'PD3',
      name: 'PD3 / INT1',
      type: 'INT',   funcs: ['GPIO', 'INT'],
      volt: '5V', curr: '40mA',
      note: 'Port D bit 3. External Interrupt 1 (INT1). Configurable as rising edge, falling edge, or low-level trigger.',
    },
    {
      num: 18,  id: 'PD4',   lbl: 'PD4',
      name: 'PD4 / OC1B',
      type: 'PWM',   funcs: ['GPIO', 'PWM'],
      volt: '5V', curr: '40mA',
      note: 'Port D bit 4. Timer/Counter1 Output Compare B (OC1B). PWM output.',
    },
    {
      num: 19,  id: 'PD5',   lbl: 'PD5',
      name: 'PD5 / OC1A',
      type: 'PWM',   funcs: ['GPIO', 'PWM'],
      volt: '5V', curr: '40mA',
      note: 'Port D bit 5. Timer/Counter1 Output Compare A (OC1A). PWM output.',
    },
    {
      num: 20,  id: 'PD6',   lbl: 'PD6',
      name: 'PD6 / ICP1',
      type: 'TIMER', funcs: ['GPIO', 'TIMER'],
      volt: '5V', curr: '40mA',
      note: 'Port D bit 6. Timer/Counter1 Input Capture Pin (ICP1). Used to capture timer value on external event.',
    },
    {
      num: 21,  id: 'PD7',   lbl: 'PD7',
      name: 'PD7 / OC2',
      type: 'PWM',   funcs: ['GPIO', 'PWM'],
      volt: '5V', curr: '40mA',
      note: 'Port D bit 7. Timer/Counter2 Output Compare (OC2). PWM output.',
    },
    {
      num: 22,  id: 'PC0',   lbl: 'PC0',
      name: 'PC0 / SCL',
      type: 'I2C',   funcs: ['GPIO', 'I2C'],
      volt: '5V', curr: '40mA',
      note: 'Port C bit 0. Two-Wire Interface clock line (TWI SCL). Open-drain with internal pull-up. Supports up to 400 kHz.',
    },

    // ── RIGHT (23–33) ─────────────────────────────────────────
    {
      num: 23,  id: 'PC1',   lbl: 'PC1',
      name: 'PC1 / SDA',
      type: 'I2C',   funcs: ['GPIO', 'I2C'],
      volt: '5V', curr: '40mA',
      note: 'Port C bit 1. Two-Wire Interface data line (TWI SDA). Open-drain with internal pull-up.',
    },
    {
      num: 24,  id: 'PC2',   lbl: 'PC2',
      name: 'PC2 / TCK',
      type: 'JTAG',  funcs: ['GPIO', 'JTAG'],
      volt: '5V', curr: '40mA',
      note: 'Port C bit 2. JTAG Test Clock input (TCK). Clocks the JTAG state machine.',
    },
    {
      num: 25,  id: 'PC3',   lbl: 'PC3',
      name: 'PC3 / TMS',
      type: 'JTAG',  funcs: ['GPIO', 'JTAG'],
      volt: '5V', curr: '40mA',
      note: 'Port C bit 3. JTAG Test Mode Select input (TMS). Controls JTAG state machine transitions.',
    },
    {
      num: 26,  id: 'PC4',   lbl: 'PC4',
      name: 'PC4 / TDO',
      type: 'JTAG',  funcs: ['GPIO', 'JTAG'],
      volt: '5V', curr: '40mA',
      note: 'Port C bit 4. JTAG Test Data Output (TDO). Serial scan chain output.',
    },
    {
      num: 27,  id: 'PC5',   lbl: 'PC5',
      name: 'PC5 / TDI',
      type: 'JTAG',  funcs: ['GPIO', 'JTAG'],
      volt: '5V', curr: '40mA',
      note: 'Port C bit 5. JTAG Test Data Input (TDI). Serial scan chain input.',
    },
    {
      num: 28,  id: 'PC6',   lbl: 'PC6',
      name: 'PC6 / TOSC1',
      type: 'XTAL',  funcs: ['GPIO', 'XTAL'],
      volt: '5V', curr: '40mA',
      note: 'Port C bit 6. Timer Oscillator pin 1 (TOSC1). Used with external 32.768 kHz watch crystal for Timer/Counter2 async operation.',
    },
    {
      num: 29,  id: 'PC7',   lbl: 'PC7',
      name: 'PC7 / TOSC2',
      type: 'XTAL',  funcs: ['GPIO', 'XTAL'],
      volt: '5V', curr: '40mA',
      note: 'Port C bit 7. Timer Oscillator pin 2 (TOSC2). Paired with TOSC1 for Timer/Counter2 asynchronous operation.',
    },
    {
      num: 30,  id: 'AVCC',  lbl: 'AVCC',
      name: 'AVCC',
      type: 'PWR',   funcs: ['PWR', 'ADC'],
      volt: '5V', curr: '200mA',
      note: 'Analog supply voltage for ADC, Port A, and the analog comparator. Must be connected to VCC even if ADC is not used. Filter with 10µH inductor and 100nF capacitor.',
    },
    {
      num: 31,  id: 'GND2',  lbl: 'GND',
      name: 'GND (Analog)',
      type: 'GND',   funcs: ['GND'],
      volt: '0V', curr: 'N/A',
      note: 'Analog ground. Connect to ground plane, preferably with a star ground topology separate from digital ground.',
    },
    {
      num: 32,  id: 'AREF',  lbl: 'AREF',
      name: 'AREF',
      type: 'ADC',   funcs: ['ADC'],
      volt: '0–5V', curr: 'N/A',
      note: 'ADC external reference voltage input. Decouple with 100nF capacitor to GND. Can use internal 2.56V bandgap or AVCC as reference instead.',
    },
    {
      num: 33,  id: 'PA7',   lbl: 'PA7',
      name: 'PA7 / ADC7',
      type: 'ADC',   funcs: ['GPIO', 'ADC'],
      volt: '0–5V', curr: '40mA',
      note: 'Port A bit 7. ADC channel 7 input. Input impedance should be kept below 10kΩ for accurate conversion.',
    },

    // ── TOP (34–44) ───────────────────────────────────────────
    {
      num: 34,  id: 'PA6',   lbl: 'PA6',
      name: 'PA6 / ADC6',
      type: 'ADC',   funcs: ['GPIO', 'ADC'],
      volt: '0–5V', curr: '40mA',
      note: 'Port A bit 6. ADC channel 6 input.',
    },
    {
      num: 35,  id: 'PA5',   lbl: 'PA5',
      name: 'PA5 / ADC5',
      type: 'ADC',   funcs: ['GPIO', 'ADC'],
      volt: '0–5V', curr: '40mA',
      note: 'Port A bit 5. ADC channel 5 input.',
    },
    {
      num: 36,  id: 'PA4',   lbl: 'PA4',
      name: 'PA4 / ADC4',
      type: 'ADC',   funcs: ['GPIO', 'ADC'],
      volt: '0–5V', curr: '40mA',
      note: 'Port A bit 4. ADC channel 4 input.',
    },
    {
      num: 37,  id: 'PA3',   lbl: 'PA3',
      name: 'PA3 / ADC3',
      type: 'ADC',   funcs: ['GPIO', 'ADC'],
      volt: '0–5V', curr: '40mA',
      note: 'Port A bit 3. ADC channel 3 input.',
    },
    {
      num: 38,  id: 'PA2',   lbl: 'PA2',
      name: 'PA2 / ADC2',
      type: 'ADC',   funcs: ['GPIO', 'ADC'],
      volt: '0–5V', curr: '40mA',
      note: 'Port A bit 2. ADC channel 2 input.',
    },
    {
      num: 39,  id: 'PA1',   lbl: 'PA1',
      name: 'PA1 / ADC1',
      type: 'ADC',   funcs: ['GPIO', 'ADC'],
      volt: '0–5V', curr: '40mA',
      note: 'Port A bit 1. ADC channel 1 input.',
    },
    {
      num: 40,  id: 'PA0',   lbl: 'PA0',
      name: 'PA0 / ADC0',
      type: 'ADC',   funcs: ['GPIO', 'ADC'],
      volt: '0–5V', curr: '40mA',
      note: 'Port A bit 0. ADC channel 0 input.',
    },
    {
      num: 41,  id: 'VCC2',  lbl: 'VCC',
      name: 'VCC',
      type: 'PWR',   funcs: ['PWR'],
      volt: '5V', curr: '200mA',
      note: 'Digital power supply. Second VCC pin — decouple with 100nF ceramic capacitor close to pin.',
    },
    {
      num: 42,  id: 'GND3',  lbl: 'GND',
      name: 'GND',
      type: 'GND',   funcs: ['GND'],
      volt: '0V', curr: 'N/A',
      note: 'Ground. Third GND pin — connect to ground plane.',
    },
    {
      num: 43,  id: 'PC6b',  lbl: 'PC6',
      name: 'PC6 (JTAG)',
      type: 'JTAG',  funcs: ['GPIO', 'JTAG'],
      volt: '5V', curr: '40mA',
      note: 'Port C bit 6. Shared JTAG boundary scan pin.',
    },
    {
      num: 44,  id: 'PD0b',  lbl: 'PD0',
      name: 'PD0 (JTAG)',
      type: 'JTAG',  funcs: ['GPIO', 'JTAG'],
      volt: '5V', curr: '40mA',
      note: 'Port D bit 0. Shared JTAG boundary scan pin.',
    },
  ],

  // ── ALTERNATE FUNCTIONS ───────────────────────────────────────
  altFuncs: {
    'PB0':   ['XCK', 'T0'],
    'PB1':   ['T1'],
    'PB2':   ['AIN0', 'INT2'],
    'PB3':   ['AIN1', 'OC0'],
    'PB4':   ['SS'],
    'PB5':   ['MOSI'],
    'PB6':   ['MISO'],
    'PB7':   ['SCK'],
    'PD0':   ['RXD'],
    'PD1':   ['TXD'],
    'PD2':   ['INT0'],
    'PD3':   ['INT1'],
    'PD4':   ['OC1B'],
    'PD5':   ['OC1A'],
    'PD6':   ['ICP1'],
    'PD7':   ['OC2'],
    'PC0':   ['SCL'],
    'PC1':   ['SDA'],
    'PC2':   ['TCK'],
    'PC3':   ['TMS'],
    'PC4':   ['TDO'],
    'PC5':   ['TDI'],
    'PC6':   ['TOSC1'],
    'PC7':   ['TOSC2'],
    'AREF':  [],
    'AVCC':  [],
  },

  // ── QUICK SPECS ───────────────────────────────────────────────
  quickSpecs: [
    { label: 'Flash',      value: '32 KB',         color: '#e0e5ec' },
    { label: 'SRAM',       value: '2 KB',           color: '#e0e5ec' },
    { label: 'EEPROM',     value: '1 KB',           color: '#e0e5ec' },
    { label: 'Max Freq',   value: '16 MHz',         color: '#c8a850' },
    { label: 'Supply',     value: '2.7–5.5V',       color: '#78c878' },
    { label: 'I/O Pins',   value: '32' },
    { label: 'ADC',        value: '8ch / 10-bit',   color: '#c8a850' },
    { label: 'USART',      value: '1×',             color: '#cc6888' },
    { label: 'SPI',        value: '1× master/slave',color: '#4a9aee' },
    { label: 'I2C (TWI)',  value: '1× 400 kHz',     color: '#9898d8' },
    { label: 'Timers',     value: '3 (2×8-bit, 1×16-bit)' },
    { label: 'PWM',        value: '4 channels',     color: '#50c8c8' },
    { label: 'JTAG',       value: 'On-chip debug',  color: '#9898d8' },
  ],

  // ── DETAILED SPECS ────────────────────────────────────────────
  dsSpecs: [
    { label: 'Architecture',   value: '8-bit AVR RISC' },
    { label: 'Flash',          value: '32 KB (10k write cycles endurance)' },
    { label: 'SRAM',           value: '2 KB' },
    { label: 'EEPROM',         value: '1 KB (100k write cycles endurance)' },
    { label: 'Max Frequency',  value: '16 MHz' },
    { label: 'Supply Voltage', value: '2.7V – 5.5V' },
    { label: 'I/O Pins',       value: '32 (with programmable pull-ups)' },
    { label: 'ADC',            value: '8-channel, 10-bit' },
    { label: 'Timers',         value: '2× 8-bit + 1× 16-bit Timer/Counter' },
    { label: 'PWM Channels',   value: '4' },
    { label: 'USART',          value: '1× full-duplex' },
    { label: 'SPI',            value: '1× master/slave' },
    { label: 'I2C (TWI)',      value: '1× up to 400 kHz' },
    { label: 'Ext Interrupts', value: '3 (INT0–INT2)' },
    { label: 'JTAG',           value: 'Boundary scan + on-chip debug' },
    { label: 'IOL (sink)',     value: '40 mA per pin max' },
    { label: 'Total I/O',      value: '200 mA total' },
    { label: 'Operating Temp', value: '−40 to +85 °C (industrial)' },
    { label: 'Package',        value: 'TQFP-44  (10×10×1.0 mm, 0.8mm pitch)' },
  ],

  // ── KEY FEATURES ──────────────────────────────────────────────
  dsFeatures: [
    '131 single-cycle instructions; most execute in one clock cycle',
    'JTAG boundary scan, on-chip debug interface, and ISP via SPI',
    '6 sleep modes: Idle, ADC Noise Reduction, Power-save, Power-down, Standby, Extended Standby',
    'Programmable watchdog timer with separate on-chip oscillator',
    'Boot loader support with independent lock bits',
    'On-chip analog comparator with programmable interrupt',
    'Brown-out detection (two selectable levels)',
    'Single-cycle hardware multiplier',
    'Internal RC oscillator (1/2/4/8 MHz) — no external crystal required',
    'Self-programmable Flash for run-time firmware updates',
    'Port A doubles as 8-channel 10-bit ADC — share analog and digital I/O',
    'QTouch® library support for capacitive touch sensing applications',
  ],
};
