window.IC_CONFIG = {

  // ── IDENTITY ──────────────────────────────────────────────────
  partName:     'ATtiny45',
  partMPN:      'ATtiny45-20SU',
  manufacturer: 'Atmel',
  package:      'DIP-8',
  pinCount:     8,

  // ── LINKS ─────────────────────────────────────────────────────
  snapPageURL:  'https://www.snapeda.com/parts/ATtiny45-20SU/Microchip/view-part/',
  downloadURL:  'https://www.snapeda.com/parts/ATtiny45-20SU/Microchip/view-part/?ref=snapeda',
  datasheetURL: 'https://ww1.microchip.com/downloads/en/DeviceDoc/ATtiny45-Data-Sheet-DS40002173A.pdf',

  // ── LAYOUT HINT (DIP-8) ───────────────────────────────────────
  dipConfig: {
    pinsPerSide:  4,
    bodyX:        62,   bodyY: 20,   bodyW: 76,  bodyH: 98,
    pinLength:    18,   pinWidthHalf: 8,
    notchSize:    4,    notchX: 6,   notchY: 6,
    textSizes:    { mfr: 8, part: 10, pkg: 7, pinCount: 6 },
    labelSize:    6,    pinNumSize: 8,   yOffset: -20,
  },

  // ── PINS ──────────────────────────────────────────────────────
  // Left side:  pins 1–4  (top → bottom)
  // Right side: pins 5–8, _rightSlot 0=top-right (pin 8) → 3=bottom-right (pin 5)
  pins: [
    {
      num:  1,
      id:   'PB5',
      lbl:  'PB5',
      name: 'PB5 / RESET / ADC0 / PCINT5',
      type: 'RESET',
      funcs: ['GPIO', 'RESET', 'ADC', 'INT'],
      volt: '5V',
      curr: '40mA',
      note: 'Active-low reset pin. Also serves as ADC channel 0 (ADC0), pin-change interrupt PCINT5, and debugWire interface. Can be reconfigured as GPIO if RSTDISBL fuse is programmed.',
    },
    {
      num:  2,
      id:   'PB3',
      lbl:  'PB3',
      name: 'PB3 / XTAL1 / CLKI / OC1B / ADC3 / PCINT3',
      type: 'XTAL',
      funcs: ['GPIO', 'XTAL', 'ADC', 'INT', 'PWM'],
      volt: '5V',
      curr: '40mA',
      note: 'Crystal oscillator input (XTAL1) or external clock input (CLKI). ADC channel 3 (ADC3). PWM output OC1B (Timer/Counter1). Pin-change interrupt PCINT3.',
    },
    {
      num:  3,
      id:   'PB4',
      lbl:  'PB4',
      name: 'PB4 / XTAL2 / CLKO / OC1B / ADC2 / PCINT4',
      type: 'XTAL',
      funcs: ['GPIO', 'XTAL', 'ADC', 'INT', 'PWM'],
      volt: '5V',
      curr: '40mA',
      note: 'Crystal oscillator output (XTAL2) or system clock output (CLKO). ADC channel 2 (ADC2). PWM output OC1B. Pin-change interrupt PCINT4.',
    },
    {
      num:  4,
      id:   'GND',
      lbl:  'GND',
      name: 'GND',
      type: 'GND',
      funcs: ['GND'],
      volt: '0V',
      curr: 'N/A',
      note: 'Ground reference. Connect to system ground plane.',
    },
    {
      num:  5,
      id:   'PB0',
      lbl:  'PB0',
      name: 'PB0 / MOSI / DI / SDA / AIN0 / OC0A / PCINT0',
      type: 'SPI',
      funcs: ['GPIO', 'SPI', 'I2C', 'ACMP', 'PWM', 'INT', 'USART'],
      volt: '5V',
      curr: '40mA',
      note: 'MOSI / DI for USI (Universal Serial Interface). SDA for USI I2C. Analog Comparator positive input (AIN0). PWM output OC0A (Timer/Counter0 Compare Match A). Pin-change interrupt PCINT0. Software USART TXD.',
      _rightSlot: 3,
    },
    {
      num:  6,
      id:   'PB1',
      lbl:  'PB1',
      name: 'PB1 / MISO / DO / AIN1 / OC0B / INT0 / PCINT1',
      type: 'SPI',
      funcs: ['GPIO', 'SPI', 'ACMP', 'PWM', 'INT', 'USART'],
      volt: '5V',
      curr: '40mA',
      note: 'MISO / DO for USI. Analog Comparator negative input (AIN1). PWM output OC0B (Timer/Counter0 Compare Match B). External interrupt INT0. Pin-change interrupt PCINT1. Software USART RXD.',
      _rightSlot: 2,
    },
    {
      num:  7,
      id:   'PB2',
      lbl:  'PB2',
      name: 'PB2 / SCK / USCK / SCL / ADC1 / T0 / INT0 / PCINT2',
      type: 'SPI',
      funcs: ['GPIO', 'SPI', 'I2C', 'ADC', 'INT'],
      volt: '5V',
      curr: '40mA',
      note: 'SCK / USCK for USI SPI. SCL for USI I2C. ADC channel 1 (ADC1). Timer0 external clock source (T0). External interrupt INT0. Pin-change interrupt PCINT2.',
      _rightSlot: 1,
    },
    {
      num:  8,
      id:   'VCC',
      lbl:  'VCC',
      name: 'VCC',
      type: 'PWR',
      funcs: ['PWR'],
      volt: '1.8–5.5V',
      curr: '200mA',
      note: 'Positive supply voltage. Operating range 1.8V–5.5V. Decouple with a 100nF ceramic capacitor placed as close as possible to the pin.',
      _rightSlot: 0,
    },
  ],

  // ── ALTERNATE FUNCTIONS ───────────────────────────────────────
  altFuncs: {
    'PB0': ['MOSI', 'DI', 'SDA', 'AIN0', 'OC0A'],
    'PB1': ['MISO', 'DO', 'AIN1', 'OC0B', 'INT0'],
    'PB2': ['SCK', 'USCK', 'SCL', 'ADC1', 'T0'],
    'PB3': ['XTAL1', 'CLKI', 'OC1B', 'ADC3'],
    'PB4': ['XTAL2', 'CLKO', 'OC1B', 'ADC2'],
    'PB5': ['RESET', 'ADC0', 'dW'],
  },

  // ── QUICK SPECS ───────────────────────────────────────────────
  quickSpecs: [
    { label: 'Flash',    value: '4 KB',                      color: '#e0e5ec' },
    { label: 'SRAM',     value: '256 Bytes',                  color: '#e0e5ec' },
    { label: 'EEPROM',   value: '256 Bytes',                  color: '#e0e5ec' },
    { label: 'Max Freq', value: '20 MHz',                     color: '#c8a850' },
    { label: 'Supply',   value: '1.8–5.5V',                   color: '#78c878' },
    { label: 'I/O Pins', value: '6' },
    { label: 'ADC',      value: '4ch / 10-bit',               color: '#c8a850' },
    { label: 'I2C',      value: 'USI (PB0/SDA, PB2/SCL)',     color: '#9898d8' },
    { label: 'Timers',   value: '2× 8-bit + PWM',             color: '#cc6888' },
  ],

  // ── DETAILED SPECS ────────────────────────────────────────────
  dsSpecs: [
    { label: 'Architecture',    value: '8-bit AVR RISC' },
    { label: 'Flash',           value: '4 KB (10k write cycles endurance)' },
    { label: 'SRAM',            value: '256 Bytes' },
    { label: 'EEPROM',          value: '256 Bytes (100k write cycles endurance)' },
    { label: 'Max Frequency',   value: '20 MHz' },
    { label: 'Supply Voltage',  value: '1.8V – 5.5V' },
    { label: 'I/O Pins',        value: '6 (with programmable pull-ups)' },
    { label: 'ADC',             value: '4-channel, 10-bit' },
    { label: 'Timers',          value: '2× 8-bit Timer/Counter with PWM' },
    { label: 'USI',             value: 'Universal Serial Interface (SPI / I2C / USART)' },
    { label: 'Ext Interrupts',  value: 'INT0 (PB1 or PB2)' },
    { label: 'PCINT',           value: '6 pins (PCINT0–PCINT5)' },
    { label: 'debugWire',       value: 'On-chip debug via RESET pin' },
    { label: 'IOL (sink)',      value: '40 mA per pin max' },
    { label: 'Total I/O',       value: '200 mA total' },
    { label: 'Operating Temp',  value: '−40 to +85 °C (industrial)' },
  ],

  // ── KEY FEATURES ──────────────────────────────────────────────
  dsFeatures: [
    '120 single-cycle instructions; most execute in one clock cycle',
    'Internal RC oscillator selectable at 8 / 4 / 2 / 1 MHz',
    'USI — Universal Serial Interface supporting SPI, I2C (TWI), and software USART',
    'Two independent 8-bit Timer/Counters with PWM outputs (OC0A, OC0B, OC1B)',
    'ISP (In-System Programming) via USI SPI — no external programmer needed',
    'Power-on Reset (POR) and programmable Brown-out Detection (BOD)',
    'External interrupt on INT0 plus 6-pin pin-change interrupt (PCINT)',
    'Watchdog timer with separate on-chip oscillator',
    '4-channel 10-bit ADC with internal 1.1V bandgap reference',
    'Analog Comparator with programmable interrupt',
    'debugWire on-chip debug interface on RESET pin',
    'Available packages: PDIP-8, SOIC-8, QFN/MLF-20 (ATtiny45V for low voltage)',
  ],
};
