// configs/pic18f4550-config.js

// configs/pic18f4550-config.js
window.IC_CONFIG = {
  partName:     'PIC18F4550',
  partMPN:      'PIC18F4550-I/P',
  manufacturer: 'MICROCHIP',
  package:      'DIP-40',
  pinCount:     40,

  snapPageURL:  'https://www.snapeda.com/parts/PIC18F4550-I%2FP/Microchip+Technology/view-part/',
  downloadURL:  'https://www.snapeda.com/parts/PIC18F4550-I%2FP/Microchip+Technology/view-part/?ref=snapeda',
  datasheetURL: 'https://ww1.microchip.com/downloads/en/DeviceDoc/39632e.pdf',

  dipConfig: { pinsPerSide: 20, bodyX: 122, bodyY: 25, bodyW: 260, bodyH: 700 },

  pins: [
    // LEFT side (pins 1-20, top to bottom)
    {num:1,  id:'MCLR',    lbl:'MCLR',  name:'MCLR / VPP / RE3',      type:'RESET',funcs:['RESET'],              volt:'5V', curr:'N/A',  note:'Master Clear (active low). Also RE3 digital input.'},
    {num:2,  id:'RA0',     lbl:'RA0',   name:'RA0 / AN0',              type:'ADC',  funcs:['GPIO','ADC'],          volt:'5V', curr:'25mA', note:'PORTA bit 0. Analog input AN0.'},
    {num:3,  id:'RA1',     lbl:'RA1',   name:'RA1 / AN1',              type:'ADC',  funcs:['GPIO','ADC'],          volt:'5V', curr:'25mA', note:'PORTA bit 1. Analog input AN1.'},
    {num:4,  id:'RA2',     lbl:'RA2',   name:'RA2 / AN2 / VREF- / CVREF',type:'ADC',funcs:['GPIO','ADC'],         volt:'5V', curr:'25mA', note:'PORTA bit 2. ADC negative reference.'},
    {num:5,  id:'RA3',     lbl:'RA3',   name:'RA3 / AN3 / VREF+',     type:'ADC',  funcs:['GPIO','ADC'],          volt:'5V', curr:'25mA', note:'PORTA bit 3. ADC positive reference.'},
    {num:6,  id:'RA4',     lbl:'RA4',   name:'RA4 / T0CKI / C1OUT',   type:'TIMER',funcs:['GPIO','TIMER','COMP'], volt:'5V', curr:'25mA', note:'PORTA bit 4. Timer0 external clock.'},
    {num:7,  id:'RA5',     lbl:'RA5',   name:'RA5 / AN4 / LVDIN / C2OUT',type:'ADC',funcs:['GPIO','ADC','COMP'],  volt:'5V', curr:'25mA', note:'PORTA bit 5. Analog input AN4.'},
    {num:8,  id:'RE0',     lbl:'RE0',   name:'RE0 / AN5',              type:'ADC',  funcs:['GPIO','ADC'],          volt:'5V', curr:'25mA', note:'PORTE bit 0. Analog input AN5.'},
    {num:9,  id:'RE1',     lbl:'RE1',   name:'RE1 / AN6',              type:'ADC',  funcs:['GPIO','ADC'],          volt:'5V', curr:'25mA', note:'PORTE bit 1. Analog input AN6.'},
    {num:10, id:'RE2',     lbl:'RE2',   name:'RE2 / AN7',              type:'ADC',  funcs:['GPIO','ADC'],          volt:'5V', curr:'25mA', note:'PORTE bit 2. Analog input AN7.'},
    {num:11, id:'VDD1',    lbl:'VDD',   name:'VDD — Power 1',          type:'PWR',  funcs:['PWR'],                 volt:'5V', curr:'N/A',  note:'Positive supply. Decouple with 100nF.'},
    {num:12, id:'VSS1',    lbl:'VSS',   name:'VSS — Ground 1',         type:'GND',  funcs:['GND'],                 volt:'0V', curr:'N/A',  note:'Ground reference.'},
    {num:13, id:'OSC1',    lbl:'OSC1',  name:'OSC1 / CLKI',            type:'XTAL', funcs:['XTAL'],                volt:'5V', curr:'N/A',  note:'Crystal oscillator input.'},
    {num:14, id:'OSC2',    lbl:'OSC2',  name:'OSC2 / CLKO / RA6',      type:'XTAL', funcs:['XTAL','GPIO'],         volt:'5V', curr:'N/A',  note:'Crystal oscillator output.'},
    {num:15, id:'RC0',     lbl:'RC0',   name:'RC0 / T1OSO / T13CKI',   type:'TIMER',funcs:['GPIO','TIMER'],        volt:'5V', curr:'25mA', note:'PORTC bit 0. Timer1 oscillator output.'},
    {num:16, id:'RC1',     lbl:'RC1',   name:'RC1 / T1OSI / CCP2',     type:'PWM',  funcs:['GPIO','TIMER','PWM'],  volt:'5V', curr:'25mA', note:'PORTC bit 1. CCP2 capture/compare/PWM.'},
    {num:17, id:'RC2',     lbl:'RC2',   name:'RC2 / CCP1',             type:'PWM',  funcs:['GPIO','PWM'],          volt:'5V', curr:'25mA', note:'PORTC bit 2. CCP1 module.'},
    {num:18, id:'VUSB',    lbl:'VUSB',  name:'VUSB — USB 3.3V Reg',   type:'USB',  funcs:['USB'],                 volt:'3.3V',curr:'N/A', note:'USB 3.3V internal regulator output.'},
    {num:19, id:'RD0',     lbl:'RD0',   name:'RD0',                    type:'GPIO', funcs:['GPIO'],                volt:'5V', curr:'25mA', note:'PORTD bit 0.'},
    {num:20, id:'RD1',     lbl:'RD1',   name:'RD1',                    type:'GPIO', funcs:['GPIO'],                volt:'5V', curr:'25mA', note:'PORTD bit 1.'},

    // RIGHT side (pins 21-40, with _rightSlot: 0=top-right, 19=bottom-right)
    {num:21, id:'RD2',  lbl:'RD2',  name:'RD2',                       type:'GPIO', funcs:['GPIO'],                 volt:'5V',curr:'25mA', _rightSlot:19, note:'PORTD bit 2.'},
    {num:22, id:'RD3',  lbl:'RD3',  name:'RD3',                       type:'GPIO', funcs:['GPIO'],                 volt:'5V',curr:'25mA', _rightSlot:18, note:'PORTD bit 3.'},
    {num:23, id:'RD4',  lbl:'RD4',  name:'RD4 / SDO',                 type:'SPI',  funcs:['GPIO','SPI'],           volt:'5V',curr:'25mA', _rightSlot:17, note:'PORTD bit 4. SPI data out.'},
    {num:24, id:'D_',   lbl:'D-',   name:'D- — USB Data Minus',       type:'USB',  funcs:['USB'],                  volt:'3.3V',curr:'N/A', _rightSlot:16, note:'USB full-speed data minus.'},
    {num:25, id:'D_P',  lbl:'D+',   name:'D+ — USB Data Plus',        type:'USB',  funcs:['USB'],                  volt:'3.3V',curr:'N/A', _rightSlot:15, note:'USB full-speed data plus.'},
    {num:26, id:'RC7',  lbl:'RC7',  name:'RC7 / RX / DT',             type:'UART', funcs:['GPIO','UART'],          volt:'5V',curr:'25mA', _rightSlot:14, note:'PORTC bit 7. USART receive.'},
    {num:27, id:'RC6',  lbl:'RC6',  name:'RC6 / TX / CK',             type:'UART', funcs:['GPIO','UART'],          volt:'5V',curr:'25mA', _rightSlot:13, note:'PORTC bit 6. USART transmit.'},
    {num:28, id:'RC5',  lbl:'RC5',  name:'RC5 / SDO',                 type:'SPI',  funcs:['GPIO','SPI'],           volt:'5V',curr:'25mA', _rightSlot:12, note:'PORTC bit 5. SPI data out.'},
    {num:29, id:'RC4',  lbl:'RC4',  name:'RC4 / SDI / SDA',           type:'SPI',  funcs:['GPIO','SPI','I2C'],    volt:'5V',curr:'25mA', _rightSlot:11, note:'PORTC bit 4. SPI data in.'},
    {num:30, id:'RD7',  lbl:'RD7',  name:'RD7 / P1D / SS',            type:'SPI',  funcs:['GPIO','SPI','PWM'],     volt:'5V',curr:'25mA', _rightSlot:10, note:'PORTD bit 7. SPI slave-select.'},
    {num:31, id:'RD6',  lbl:'RD6',  name:'RD6 / P1C',                 type:'PWM',  funcs:['GPIO','PWM'],           volt:'5V',curr:'25mA', _rightSlot:9,  note:'PORTD bit 6. PWM output.'},
    {num:32, id:'RD5',  lbl:'RD5',  name:'RD5 / P1B',                 type:'PWM',  funcs:['GPIO','PWM'],           volt:'5V',curr:'25mA', _rightSlot:8,  note:'PORTD bit 5. PWM output.'},
    {num:33, id:'VDD2', lbl:'VDD',  name:'VDD — Power 2',              type:'PWR',  funcs:['PWR'],                  volt:'5V',curr:'N/A',  _rightSlot:7,  note:'Positive supply voltage 2.'},
    {num:34, id:'VSS2', lbl:'VSS',  name:'VSS — Ground 2',             type:'GND',  funcs:['GND'],                  volt:'0V',curr:'N/A',  _rightSlot:6,  note:'Ground reference 2.'},
    {num:35, id:'RB0',  lbl:'RB0',  name:'RB0 / AN12 / INT0 / FLT0',  type:'INT',  funcs:['GPIO','ADC','INT'],     volt:'5V',curr:'25mA', _rightSlot:5,  note:'PORTB bit 0. External interrupt.'},
    {num:36, id:'RB1',  lbl:'RB1',  name:'RB1 / AN10 / INT1',         type:'GPIO', funcs:['GPIO','ADC','INT'],     volt:'5V',curr:'25mA', _rightSlot:4,  note:'PORTB bit 1. External interrupt INT1.'},
    {num:37, id:'RB2',  lbl:'RB2',  name:'RB2 / AN8 / INT2',          type:'GPIO', funcs:['GPIO','ADC','INT'],     volt:'5V',curr:'25mA', _rightSlot:3,  note:'PORTB bit 2. External interrupt INT2.'},
    {num:38, id:'RB3',  lbl:'RB3',  name:'RB3 / AN9 / CCP2',          type:'GPIO', funcs:['GPIO','ADC','PWM'],     volt:'5V',curr:'25mA', _rightSlot:2,  note:'PORTB bit 3. CCP2 alternate pin.'},
    {num:39, id:'RB4',  lbl:'RB4',  name:'RB4 / AN11 / KBI0',         type:'GPIO', funcs:['GPIO','ADC','INT'],     volt:'5V',curr:'25mA', _rightSlot:1,  note:'PORTB bit 4. Interrupt-on-change.'},
    {num:40, id:'RB5',  lbl:'RB5',  name:'RB5 / KBI1 / PGM',          type:'GPIO', funcs:['GPIO','INT','RESET'],   volt:'5V',curr:'25mA', _rightSlot:0,  note:'PORTB bit 5. Low-voltage ICSP enable.'},
  ],

  altFuncs: {
    'MCLR':['VPP','RE3'],
    'RA2':['AN2','VREF-','CVREF'],'RA3':['AN3','VREF+'],
    'RA4':['T0CKI','C1OUT'],'RA5':['AN4','LVDIN','C2OUT'],
    'OSC1':['CLKI'],'OSC2':['CLKO','RA6'],
    'RC0':['T1OSO','T13CKI'],'RC1':['T1OSI','CCP2'],'RC2':['CCP1'],
    'RC6':['TX','CK'],'RC7':['RX','DT'],
    'RD4':['SDO'],'RD5':['P1B'],'RD6':['P1C'],'RD7':['P1D','SS'],
    'RB0':['AN12','INT0','FLT0'],'RB1':['AN10','INT1'],
    'RB2':['AN8','INT2'],'RB3':['AN9','CCP2'],
    'RB4':['AN11','KBI0'],'RB5':['KBI1','PGM'],
  },

  quickSpecs: [
    {label:'Flash',        value:'24 KB', color:'#e0e5ec'},
    {label:'SRAM',         value:'2 KB', color:'#e0e5ec'},
    {label:'EEPROM',       value:'256 bytes', color:'#e0e5ec'},
    {label:'Max Freq',     value:'48 MHz (USB)', color:'#c8a850'},
    {label:'Supply',       value:'2.0–5.5V', color:'#78c878'},
    {label:'I/O Pins',     value:'35 (5 ports)', color:'#e0e5ec'},
    {label:'ADC',          value:'10-bit, 13 ch', color:'#c8a850'},
    {label:'USB',          value:'Full-Speed (12 Mb/s)', color:'#a78bfa'},
    {label:'Interfaces',   value:'USB + SPI + I²C + USART', color:'#c8a850'},
  ],

  dsSpecs: [
    {label:'Architecture',    value:'8-bit PIC18 RISC'},
    {label:'Flash',           value:'24 KB (12K × 16-bit words)'},
    {label:'SRAM',            value:'2 KB'},
    {label:'EEPROM',          value:'256 bytes'},
    {label:'Max Frequency',   value:'48 MHz (USB PLL mode)'},
    {label:'Supply Voltage',  value:'2.0V – 5.5V'},
    {label:'I/O Pins',        value:'35 (Ports A/B/C/D/E)'},
    {label:'ADC',             value:'10-bit, 13 channels'},
    {label:'Timers',          value:'Timer0(8/16-bit) + Timer1 + Timer2 + Timer3'},
    {label:'CCP',             value:'1× Enhanced CCP (PWM) + 1× CCP'},
    {label:'USB',             value:'Full-Speed (12 Mb/s) — integrated transceiver'},
    {label:'USART',           value:'1× Enhanced USART (EUART)'},
    {label:'MSSP',            value:'SPI (all 4 modes) + I²C master/slave'},
    {label:'Comparators',     value:'2× analog comparators'},
    {label:'Package',         value:'DIP-40, TQFP-44, QFN-44'},
  ],

  dsFeatures: [
    'USB 2.0 full-speed (12 Mb/s) with integrated 3.3V regulator',
    '10-bit ADC with 13 multiplexed channels',
    'Enhanced CCP module: 1–16 bit resolution PWM',
    'MSSP module: SPI and I²C master/slave',
    'Enhanced USART (EUART) with auto-baud detection',
    'PLL clock multiplier allows 48 MHz CPU operation from 8 MHz crystal',
    '4 external interrupt pins (INT0–INT2 + 4× interrupt-on-change PORTB)',
    'In-Circuit Serial Programming (ICSP)',
    'Brown-out Reset, Power-on Reset, Watchdog Timer',
    '5 I/O ports: PORTA (6), PORTB (8), PORTC (7), PORTD (8), PORTE (3)',
  ],
};
