// configs/msp430fr5994-config.js
window.IC_CONFIG = {
  // ── IDENTITY ──────────────────────────────────────────────────
  partName:     'MSP430FR5994',
  partMPN:      'MSP430FR5994IPN',
  manufacturer: 'Texas Instruments',
  package:      'LQFP-80',
  pinCount:     80,

  // ── LINKS ─────────────────────────────────────────────────────
  snapPageURL:  'https://www.snapeda.com/parts/MSP430FR5994IPN/Texas%20Instruments/view-part/',
  downloadURL:  'https://www.snapeda.com/parts/MSP430FR5994IPN/Texas%20Instruments/download/',
  datasheetURL: 'https://www.ti.com/lit/ds/symlink/msp430fr5994.pdf',

  // ── LAYOUT HINT (QFP only) ────────────────────────────────────
  // QFP pins: 20 per side (80/4 = 20)
  qfpConfig: {
    pinsPerSide: 20,
    bodySize: 400,
    pinLength: 24,
    pinWidth: 14,
    pinGap: 2
  },

  // ── PINS ──────────────────────────────────────────────────────
  // QFP ordering: LEFT (pins 1-20, top→bottom), BOTTOM (pins 21-40, left→right),
  //               RIGHT (pins 41-60, bottom→top), TOP (pins 61-80, right→left)
  pins: [
    // ========== LEFT SIDE: pins 1-20 (top to bottom) ==========
    { num: 1,  id: 'P2.0',  lbl: 'P2.0',  name: 'P2.0 / UCA0TXD / UCA0SIMO / BSLTX', type: 'GPIO',  funcs: ['GPIO', 'UART', 'SPI'], volt: '3.3V', curr: '6 mA', note: 'Port 2.0. eUSCI_A0 TXD (UART) or SIMO (SPI). BSL TX pin (UART BSL mode).' },
    { num: 2,  id: 'P2.1',  lbl: 'P2.1',  name: 'P2.1 / UCA0RXD / UCA0SOMI / BSLRX', type: 'GPIO',  funcs: ['GPIO', 'UART', 'SPI'], volt: '3.3V', curr: '6 mA', note: 'Port 2.1. eUSCI_A0 RXD (UART) or SOMI (SPI). BSL RX pin (UART BSL mode).' },
    { num: 3,  id: 'P2.2',  lbl: 'P2.2',  name: 'P2.2 / UCA0CLK / TA0.2', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 2.2. eUSCI_A0 CLK (SPI). TimerA0 CCR2 output (TA0.2).' },
    { num: 4,  id: 'P2.3',  lbl: 'P2.3',  name: 'P2.3 / UCB0STE / TA1.2', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 2.3. eUSCI_B0 STE (SPI). TimerA1 CCR2 output (TA1.2).' },
    { num: 5,  id: 'P2.4',  lbl: 'P2.4',  name: 'P2.4 / TA0.2 / TB0.4', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 2.4. TimerA0 CCR2 or TimerB0 CCR4 PWM output.' },
    { num: 6,  id: 'P2.5',  lbl: 'P2.5',  name: 'P2.5 / TA0.1 / TB0.3', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 2.5. TimerA0 CCR1 or TimerB0 CCR3 PWM output.' },
    { num: 7,  id: 'P2.6',  lbl: 'P2.6',  name: 'P2.6 / UCB2SCL / UCB2CLK / TB0.2', type: 'GPIO',  funcs: ['GPIO', 'I2C', 'SPI', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 2.6. eUSCI_B2 SCL (I2C) / CLK (SPI). TimerB0 CCR2 PWM (TB0.2).' },
    { num: 8,  id: 'P2.7',  lbl: 'P2.7',  name: 'P2.7 / TA1.0 / TB0.1', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 2.7. TimerA1 CCR0 or TimerB0 CCR1 PWM output.' },
    { num: 9,  id: 'DVCC1', lbl: 'VCC',   name: 'DVCC1 — Digital Power Supply 1', type: 'PWR',   funcs: ['PWR'], volt: '3.3V', curr: 'N/A', note: 'Digital power supply 1 (1.8V–3.6V). Decouple with 100nF + 10µF capacitors.' },
    { num: 10, id: 'DVSS1', lbl: 'GND',   name: 'DVSS1 — Digital Ground 1', type: 'GND',   funcs: ['GND'], volt: '0V',   curr: 'N/A', note: 'Digital ground 1. Connect to system ground plane.' },
    { num: 11, id: 'P1.0',  lbl: 'P1.0',  name: 'P1.0 / TA0CLK / DMAE0 / COUT', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 1.0. TimerA0 external clock. DMA trigger. Comparator_E output.' },
    { num: 12, id: 'P1.1',  lbl: 'P1.1',  name: 'P1.1 / TA0.0 / COUT', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'PWM', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 1.1. TimerA0 CCR0 PWM output. Comparator_E output.' },
    { num: 13, id: 'P1.2',  lbl: 'P1.2',  name: 'P1.2 / TA1CLK / COUT', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 1.2. TimerA1 external clock. Comparator_E output.' },
    { num: 14, id: 'P1.3',  lbl: 'P1.3',  name: 'P1.3 / TA1.0 / C0', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'PWM', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 1.3. TimerA1 CCR0 PWM output. Comparator_E input C0.' },
    { num: 15, id: 'P1.4',  lbl: 'P1.4',  name: 'P1.4 / TA1.1 / C1', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'PWM', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 1.4. TimerA1 CCR1 PWM output. Comparator_E input C1.' },
    { num: 16, id: 'P1.5',  lbl: 'P1.5',  name: 'P1.5 / TA1.2 / C2', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'PWM', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 1.5. TimerA1 CCR2 PWM output. Comparator_E input C2.' },
    { num: 17, id: 'P1.6',  lbl: 'P1.6',  name: 'P1.6 / UCB0SDA / C3 / BSLSDA', type: 'GPIO',  funcs: ['GPIO', 'I2C', 'SPI', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 1.6. eUSCI_B0 SDA (I2C). Comparator_E input C3. BSL SDA (I2C BSL mode).' },
    { num: 18, id: 'P1.7',  lbl: 'P1.7',  name: 'P1.7 / UCB0SCL / C4 / BSLSCL', type: 'GPIO',  funcs: ['GPIO', 'I2C', 'SPI', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 1.7. eUSCI_B0 SCL (I2C). Comparator_E input C4. BSL SCL (I2C BSL mode).' },
    { num: 19, id: 'AVSS1', lbl: 'AGND',  name: 'AVSS1 — Analog Ground 1', type: 'GND',   funcs: ['GND'], volt: '0V',   curr: 'N/A', note: 'Analog ground 1.' },
    { num: 20, id: 'AVCC1', lbl: 'AVCC',  name: 'AVCC1 — Analog Power Supply 1', type: 'PWR',   funcs: ['PWR'], volt: '3.3V', curr: 'N/A', note: 'Analog power supply 1. Decouple with 100nF + 1µF caps.' },

    // ========== BOTTOM SIDE: pins 21-40 (left to right) ==========
    { num: 21, id: 'P6.0',  lbl: 'P6.0',  name: 'P6.0 / A0 / C5', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 6.0. ADC12_B channel A0. Comparator_E input C5.' },
    { num: 22, id: 'P6.1',  lbl: 'P6.1',  name: 'P6.1 / A1 / C6', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 6.1. ADC12_B channel A1. Comparator_E input C6.' },
    { num: 23, id: 'P6.2',  lbl: 'P6.2',  name: 'P6.2 / A2 / C7', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 6.2. ADC12_B channel A2. Comparator_E input C7.' },
    { num: 24, id: 'P6.3',  lbl: 'P6.3',  name: 'P6.3 / A3 / C8', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 6.3. ADC12_B channel A3. Comparator_E input C8.' },
    { num: 25, id: 'P6.4',  lbl: 'P6.4',  name: 'P6.4 / A4 / C9', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 6.4. ADC12_B channel A4. Comparator_E input C9.' },
    { num: 26, id: 'P6.5',  lbl: 'P6.5',  name: 'P6.5 / A5 / C10', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 6.5. ADC12_B channel A5. Comparator_E input C10.' },
    { num: 27, id: 'P6.6',  lbl: 'P6.6',  name: 'P6.6 / A6 / C11 / VREF+', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 6.6. ADC12_B A6. Comparator_E C11. External reference VREF+.' },
    { num: 28, id: 'P6.7',  lbl: 'P6.7',  name: 'P6.7 / A7 / C12 / VREF-', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 6.7. ADC12_B A7. Comparator_E C12. External reference VREF-.' },
    { num: 29, id: 'AVSS2', lbl: 'AGND',  name: 'AVSS2 — Analog Ground 2', type: 'GND',   funcs: ['GND'], volt: '0V',   curr: 'N/A', note: 'Analog ground 2.' },
    { num: 30, id: 'AVCC2', lbl: 'AVCC',  name: 'AVCC2 — Analog Power Supply 2', type: 'PWR',   funcs: ['PWR'], volt: '3.3V', curr: 'N/A', note: 'Analog power supply 2.' },
    { num: 31, id: 'P5.0',  lbl: 'P5.0',  name: 'P5.0 / A8 / C13 / VREF+', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 5.0. ADC12_B A8. Comparator_E C13. External positive reference VREF+.' },
    { num: 32, id: 'P5.1',  lbl: 'P5.1',  name: 'P5.1 / A9 / C14 / VREF-', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 5.1. ADC12_B A9. Comparator_E C14. External negative reference VREF-.' },
    { num: 33, id: 'P5.2',  lbl: 'P5.2',  name: 'P5.2 / A10 / C15', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'ACMP'], volt: '3.3V', curr: '6 mA', note: 'Port 5.2. ADC12_B channel A10. Comparator_E input C15.' },
    { num: 34, id: 'P5.3',  lbl: 'P5.3',  name: 'P5.3 / A11', type: 'GPIO',  funcs: ['GPIO', 'ADC'], volt: '3.3V', curr: '6 mA', note: 'Port 5.3. ADC12_B channel A11.' },
    { num: 35, id: 'P5.4',  lbl: 'XIN',   name: 'P5.4 / LFXIN / LFIN', type: 'XTAL',  funcs: ['XTAL', 'GPIO'], volt: '3.3V', curr: 'N/A', note: 'Port 5.4. 32.768 kHz low-frequency crystal input (LFXT).' },
    { num: 36, id: 'P5.5',  lbl: 'XOUT',  name: 'P5.5 / LFXOUT / LFOUT', type: 'XTAL',  funcs: ['XTAL', 'GPIO'], volt: '3.3V', curr: 'N/A', note: 'Port 5.5. 32.768 kHz crystal output. Connect crystal between P5.4 and P5.5.' },
    { num: 37, id: 'P5.6',  lbl: 'HFIN',  name: 'P5.6 / HFXIN / HFIN', type: 'XTAL',  funcs: ['XTAL', 'GPIO'], volt: '3.3V', curr: 'N/A', note: 'Port 5.6. High-frequency crystal input (HFXT). Supports 4-32 MHz.' },
    { num: 38, id: 'P5.7',  lbl: 'HFOUT', name: 'P5.7 / HFXOUT / HFOUT', type: 'XTAL',  funcs: ['XTAL', 'GPIO'], volt: '3.3V', curr: 'N/A', note: 'Port 5.7. High-frequency crystal output.' },
    { num: 39, id: 'DVSS2', lbl: 'GND',   name: 'DVSS2 — Digital Ground 2', type: 'GND',   funcs: ['GND'], volt: '0V',   curr: 'N/A', note: 'Digital ground 2.' },
    { num: 40, id: 'DVCC2', lbl: 'VCC',   name: 'DVCC2 — Digital Power Supply 2', type: 'PWR',   funcs: ['PWR'], volt: '3.3V', curr: 'N/A', note: 'Digital power supply 2.' },

    // ========== RIGHT SIDE: pins 41-60 (bottom to top) ==========
    { num: 41, id: 'P3.0',  lbl: 'P3.0',  name: 'P3.0 / UCB0STE / UCA1CLK', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'UART'], volt: '3.3V', curr: '6 mA', note: 'Port 3.0. eUSCI_B0 STE (SPI). eUSCI_A1 CLK.' },
    { num: 42, id: 'P3.1',  lbl: 'P3.1',  name: 'P3.1 / UCB0CLK / UCB0SCL / UCA1STE', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'I2C', 'UART'], volt: '3.3V', curr: '6 mA', note: 'Port 3.1. eUSCI_B0 CLK/SCL. eUSCI_A1 STE.' },
    { num: 43, id: 'P3.2',  lbl: 'P3.2',  name: 'P3.2 / UCB0SIMO / UCB0SDA / UCA1TXD', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'I2C', 'UART'], volt: '3.3V', curr: '6 mA', note: 'Port 3.2. eUSCI_B0 SIMO/SDA. eUSCI_A1 TXD.' },
    { num: 44, id: 'P3.3',  lbl: 'P3.3',  name: 'P3.3 / UCB0SOMI / UCA1RXD', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'UART'], volt: '3.3V', curr: '6 mA', note: 'Port 3.3. eUSCI_B0 SOMI. eUSCI_A1 RXD.' },
    { num: 45, id: 'P3.4',  lbl: 'P3.4',  name: 'P3.4 / UCA1TXD / UCA1SIMO', type: 'GPIO',  funcs: ['GPIO', 'UART', 'SPI'], volt: '3.3V', curr: '6 mA', note: 'Port 3.4. eUSCI_A1 TXD or SIMO.' },
    { num: 46, id: 'P3.5',  lbl: 'P3.5',  name: 'P3.5 / UCA1RXD / UCA1SOMI', type: 'GPIO',  funcs: ['GPIO', 'UART', 'SPI'], volt: '3.3V', curr: '6 mA', note: 'Port 3.5. eUSCI_A1 RXD or SOMI.' },
    { num: 47, id: 'P3.6',  lbl: 'P3.6',  name: 'P3.6 / UCB2SDA / UCB2SIMO / TA4.1', type: 'GPIO',  funcs: ['GPIO', 'I2C', 'SPI', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 3.6. eUSCI_B2 SDA/SIMO. TimerA4 CCR1 PWM.' },
    { num: 48, id: 'P3.7',  lbl: 'P3.7',  name: 'P3.7 / UCB1STE / TB0CLK', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'TIMER'], volt: '3.3V', curr: '6 mA', note: 'Port 3.7. eUSCI_B1 STE. TimerB0 external clock.' },
    { num: 49, id: 'DVSS3', lbl: 'GND',   name: 'DVSS3 — Digital Ground 3', type: 'GND',   funcs: ['GND'], volt: '0V',   curr: 'N/A', note: 'Digital ground 3.' },
    { num: 50, id: 'DVCC3', lbl: 'VCC',   name: 'DVCC3 — Digital Power Supply 3', type: 'PWR',   funcs: ['PWR'], volt: '3.3V', curr: 'N/A', note: 'Digital power supply 3.' },
    { num: 51, id: 'P4.0',  lbl: 'P4.0',  name: 'P4.0 / UCB1CLK / UCB1SCL / UCA2STE', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'I2C', 'UART'], volt: '3.3V', curr: '6 mA', note: 'Port 4.0. eUSCI_B1 CLK/SCL. eUSCI_A2 STE.' },
    { num: 52, id: 'P4.1',  lbl: 'P4.1',  name: 'P4.1 / UCB1SIMO / UCB1SDA / UCA2TXD', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'I2C', 'UART'], volt: '3.3V', curr: '6 mA', note: 'Port 4.1. eUSCI_B1 SIMO/SDA. eUSCI_A2 TXD.' },
    { num: 53, id: 'P4.2',  lbl: 'P4.2',  name: 'P4.2 / UCB1SOMI / UCA2RXD', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'UART'], volt: '3.3V', curr: '6 mA', note: 'Port 4.2. eUSCI_B1 SOMI. eUSCI_A2 RXD.' },
    { num: 54, id: 'P4.3',  lbl: 'P4.3',  name: 'P4.3 / UCB1STE / UCA2CLK', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'UART'], volt: '3.3V', curr: '6 mA', note: 'Port 4.3. eUSCI_B1 STE. eUSCI_A2 CLK.' },
    { num: 55, id: 'P4.4',  lbl: 'P4.4',  name: 'P4.4 / UCA2TXD / UCA2SIMO / TA4.1 / TB0.1', type: 'GPIO',  funcs: ['GPIO', 'UART', 'SPI', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 4.4. eUSCI_A2 TXD/SIMO. TimerA4 CCR1 or TimerB0 CCR1 PWM.' },
    { num: 56, id: 'P4.5',  lbl: 'P4.5',  name: 'P4.5 / UCA2RXD / UCA2SOMI / TB0.0', type: 'GPIO',  funcs: ['GPIO', 'UART', 'SPI', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 4.5. eUSCI_A2 RXD/SOMI. TimerB0 CCR0 PWM.' },
    { num: 57, id: 'P4.6',  lbl: 'P4.6',  name: 'P4.6 / UCA2CLK / TB0.3', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 4.6. eUSCI_A2 CLK. TimerB0 CCR3 PWM.' },
    { num: 58, id: 'P4.7',  lbl: 'P4.7',  name: 'P4.7 / UCB2STE / TB0.4', type: 'GPIO',  funcs: ['GPIO', 'SPI', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 4.7. eUSCI_B2 STE. TimerB0 CCR4 PWM.' },
    { num: 59, id: 'P7.7',  lbl: 'P7.7',  name: 'P7.7 / TB0.5 / SMCLK', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 7.7. TimerB0 CCR5 PWM. SMCLK output.' },
    { num: 60, id: 'P7.6',  lbl: 'P7.6',  name: 'P7.6 / TB0.6 / ACLK', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 7.6. TimerB0 CCR6 PWM. ACLK output.' },

    // ========== TOP SIDE: pins 61-80 (right to left) ==========
    { num: 61, id: 'P7.5',  lbl: 'P7.5',  name: 'P7.5 / TA4.1', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 7.5. TimerA4 CCR1 PWM output.' },
    { num: 62, id: 'P7.4',  lbl: 'P7.4',  name: 'P7.4 / TA4.0', type: 'GPIO',  funcs: ['GPIO', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 7.4. TimerA4 CCR0 PWM output.' },
    { num: 63, id: 'P7.3',  lbl: 'P7.3',  name: 'P7.3 / TA4CLK / A15', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'TIMER'], volt: '3.3V', curr: '6 mA', note: 'Port 7.3. TimerA4 external clock. ADC12_B channel A15.' },
    { num: 64, id: 'P7.2',  lbl: 'P7.2',  name: 'P7.2 / TA0.2 / A14', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 7.2. TimerA0 CCR2 PWM. ADC12_B channel A14.' },
    { num: 65, id: 'P7.1',  lbl: 'P7.1',  name: 'P7.1 / TA0.1 / A13', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 7.1. TimerA0 CCR1 PWM. ADC12_B channel A13.' },
    { num: 66, id: 'P7.0',  lbl: 'P7.0',  name: 'P7.0 / TA0.0 / A12', type: 'GPIO',  funcs: ['GPIO', 'ADC', 'TIMER', 'PWM'], volt: '3.3V', curr: '6 mA', note: 'Port 7.0. TimerA0 CCR0 PWM. ADC12_B channel A12.' },
    { num: 67, id: 'RST',   lbl: 'RST',   name: 'RST / NMI / SBWTDIO', type: 'RESET', funcs: ['RESET', 'INT'], volt: '3.3V', curr: 'N/A', note: 'Active-low reset. Non-maskable interrupt. Spy-Bi-Wire data. Pull up via 47kΩ to DVCC.' },
    { num: 68, id: 'TEST',  lbl: 'TEST',  name: 'TEST / SBWTCK', type: 'RESET', funcs: ['RESET'], volt: '3.3V', curr: 'N/A', note: 'JTAG test clock / Spy-Bi-Wire clock. Pull to GND via 100Ω for normal operation.' },
    { num: 69, id: 'P8.0',  lbl: 'P8.0',  name: 'P8.0 / UCA3STE / UCA3SOMI', type: 'GPIO',  funcs: ['GPIO', 'UART', 'SPI'], volt: '3.3V', curr: '6 mA', note: 'Port 8.0. eUSCI_A3 STE or SOMI.' },
    { num: 70, id: 'P8.1',  lbl: 'P8.1',  name: 'P8.1 / UCA3CLK', type: 'GPIO',  funcs: ['GPIO', 'UART', 'SPI'], volt: '3.3V', curr: '6 mA', note: 'Port 8.1. eUSCI_A3 CLK.' },
    { num: 71, id: 'DVSS4', lbl: 'GND',   name: 'DVSS4 — Digital Ground 4', type: 'GND',   funcs: ['GND'], volt: '0V',   curr: 'N/A', note: 'Digital ground 4.' },
    { num: 72, id: 'DVCC4', lbl: 'VCC',   name: 'DVCC4 — Digital Power Supply 4', type: 'PWR',   funcs: ['PWR'], volt: '3.3V', curr: 'N/A', note: 'Digital power supply 4.' },
    { num: 73, id: 'P8.2',  lbl: 'P8.2',  name: 'P8.2 / UCA3TXD / UCA3SIMO', type: 'GPIO',  funcs: ['GPIO', 'UART', 'SPI'], volt: '3.3V', curr: '6 mA', note: 'Port 8.2. eUSCI_A3 TXD or SIMO.' },
    { num: 74, id: 'P8.3',  lbl: 'P8.3',  name: 'P8.3 / UCA3RXD / UCA3SOMI', type: 'GPIO',  funcs: ['GPIO', 'UART', 'SPI'], volt: '3.3V', curr: '6 mA', note: 'Port 8.3. eUSCI_A3 RXD or SOMI.' },
    { num: 75, id: 'PJ.0',  lbl: 'PJ.0',  name: 'PJ.0 / TDI / TCLK', type: 'GPIO',  funcs: ['GPIO'], volt: '3.3V', curr: '6 mA', note: 'Port J.0. JTAG TDI / TCLK in 4-wire JTAG mode.' },
    { num: 76, id: 'PJ.1',  lbl: 'PJ.1',  name: 'PJ.1 / TDO / TDI', type: 'GPIO',  funcs: ['GPIO'], volt: '3.3V', curr: '6 mA', note: 'Port J.1. JTAG TDO / TDI in 4-wire JTAG mode.' },
    { num: 77, id: 'PJ.2',  lbl: 'PJ.2',  name: 'PJ.2 / TMS', type: 'GPIO',  funcs: ['GPIO'], volt: '3.3V', curr: '6 mA', note: 'Port J.2. JTAG TMS in 4-wire JTAG mode.' },
    { num: 78, id: 'PJ.3',  lbl: 'PJ.3',  name: 'PJ.3 / TCK', type: 'GPIO',  funcs: ['GPIO'], volt: '3.3V', curr: '6 mA', note: 'Port J.3. JTAG TCK in 4-wire JTAG mode.' },
    { num: 79, id: 'PJ.4',  lbl: 'PJ.4',  name: 'PJ.4 / LFXIN', type: 'XTAL',  funcs: ['XTAL', 'GPIO'], volt: '3.3V', curr: 'N/A', note: 'Port J.4. Alternate LFXT input (32.768 kHz crystal).' },
    { num: 80, id: 'PJ.5',  lbl: 'PJ.5',  name: 'PJ.5 / LFXOUT', type: 'XTAL',  funcs: ['XTAL', 'GPIO'], volt: '3.3V', curr: 'N/A', note: 'Port J.5. Alternate LFXT output.' }
  ],

  // ── ALTERNATE FUNCTIONS ───────────────────────────────────────
  altFuncs: {
    'P1.0': ['TA0CLK', 'DMAE0', 'COUT'], 'P1.1': ['TA0.0', 'COUT'], 'P1.2': ['TA1CLK', 'COUT'],
    'P1.3': ['TA1.0', 'C0'], 'P1.4': ['TA1.1', 'C1'], 'P1.5': ['TA1.2', 'C2'],
    'P1.6': ['UCB0SDA', 'C3', 'BSLSDA'], 'P1.7': ['UCB0SCL', 'C4', 'BSLSCL'],
    'P2.0': ['UCA0TXD', 'UCA0SIMO', 'BSLTX'], 'P2.1': ['UCA0RXD', 'UCA0SOMI', 'BSLRX'],
    'P2.2': ['UCA0CLK', 'TA0.2'], 'P2.3': ['UCB0STE', 'TA1.2'],
    'P2.4': ['TA0.2', 'TB0.4'], 'P2.5': ['TA0.1', 'TB0.3'],
    'P2.6': ['UCB2SCL', 'UCB2CLK', 'TB0.2'], 'P2.7': ['TA1.0', 'TB0.1'],
    'P3.0': ['UCB0STE', 'UCA1CLK'], 'P3.1': ['UCB0CLK', 'UCB0SCL', 'UCA1STE'],
    'P3.2': ['UCB0SIMO', 'UCB0SDA', 'UCA1TXD'], 'P3.3': ['UCB0SOMI', 'UCA1RXD'],
    'P3.4': ['UCA1TXD', 'UCA1SIMO'], 'P3.5': ['UCA1RXD', 'UCA1SOMI'],
    'P3.6': ['UCB2SDA', 'UCB2SIMO', 'TA4.1'], 'P3.7': ['UCB1STE', 'TB0CLK'],
    'P4.0': ['UCB1CLK', 'UCB1SCL', 'UCA2STE'], 'P4.1': ['UCB1SIMO', 'UCB1SDA', 'UCA2TXD'],
    'P4.2': ['UCB1SOMI', 'UCA2RXD'], 'P4.3': ['UCB1STE', 'UCA2CLK'],
    'P4.4': ['UCA2TXD', 'UCA2SIMO', 'TA4.1', 'TB0.1'], 'P4.5': ['UCA2RXD', 'UCA2SOMI', 'TB0.0'],
    'P4.6': ['UCA2CLK', 'TB0.3'], 'P4.7': ['UCB2STE', 'TB0.4'],
    'P5.0': ['A8', 'C13', 'VREF+'], 'P5.1': ['A9', 'C14', 'VREF-'],
    'P5.2': ['A10', 'C15'], 'P5.3': ['A11'],
    'P5.4': ['LFXIN', 'LFIN'], 'P5.5': ['LFXOUT', 'LFOUT'],
    'P5.6': ['HFXIN', 'HFIN'], 'P5.7': ['HFXOUT', 'HFOUT'],
    'P6.0': ['A0', 'C5'], 'P6.1': ['A1', 'C6'], 'P6.2': ['A2', 'C7'], 'P6.3': ['A3', 'C8'],
    'P6.4': ['A4', 'C9'], 'P6.5': ['A5', 'C10'], 'P6.6': ['A6', 'C11', 'VREF+'], 'P6.7': ['A7', 'C12', 'VREF-'],
    'P7.0': ['TA0.0', 'A12'], 'P7.1': ['TA0.1', 'A13'], 'P7.2': ['TA0.2', 'A14'],
    'P7.3': ['TA4CLK', 'A15'], 'P7.4': ['TA4.0'], 'P7.5': ['TA4.1'],
    'P7.6': ['TB0.6', 'ACLK'], 'P7.7': ['TB0.5', 'SMCLK'],
    'P8.0': ['UCA3STE', 'UCA3SOMI'], 'P8.1': ['UCA3CLK'],
    'P8.2': ['UCA3TXD', 'UCA3SIMO'], 'P8.3': ['UCA3RXD', 'UCA3SOMI'],
    'PJ.0': ['TDI', 'TCLK'], 'PJ.1': ['TDO', 'TDI'], 'PJ.2': ['TMS'], 'PJ.3': ['TCK'],
    'PJ.4': ['LFXIN'], 'PJ.5': ['LFXOUT'],
    'RST': ['NMI', 'SBWTDIO'], 'TEST': ['SBWTCK']
  },

  // ── QUICK SPECS (right-panel sidebar summary) ─────────────────
  quickSpecs: [
    { label: 'Architecture',  value: '16-bit RISC MSP430CPUXV2', color: '#e0e5ec' },
    { label: 'FRAM',          value: '256 KB',                   color: '#e0e5ec' },
    { label: 'SRAM',          value: '8 KB (4KB shared w/ LEA)', color: '#e0e5ec' },
    { label: 'Max Freq',      value: '16 MHz',                   color: '#c8a850' },
    { label: 'Supply',        value: '1.8–3.6V',                 color: '#78c878' },
    { label: 'I/O Pins',      value: '68',                       color: '#e0e5ec' },
    { label: 'ADC',           value: '12-bit, 20 ext ch (ADC12_B)', color: '#c8a850' },
    { label: 'LEA',           value: 'DSP Accelerator (FFT/FIR)', color: '#a78bfa' },
    { label: 'eUSCI',         value: '4× A (UART/SPI) + 4× B (I2C/SPI)', color: '#4a9aee' },
    { label: 'Timers',        value: 'TB0(7) TA0/TA1/TA4(3)',    color: '#50c8c8' },
    { label: 'Package',       value: 'LQFP-80',                  color: '#e0e5ec' }
  ],

  // ── DETAILED SPECS (Datasheet tab table) ──────────────────────
  dsSpecs: [
    { label: 'Architecture',      value: '16-bit RISC (MSP430CPUXV2), 27 instructions' },
    { label: 'FRAM',              value: '256 KB program + 0.5 KB info' },
    { label: 'SRAM',              value: '8 KB (4 KB shared with LEA memory)' },
    { label: 'Max Frequency',     value: '16 MHz (calibrated DCO)' },
    { label: 'Supply Voltage',    value: '1.8V – 3.6V' },
    { label: 'Active Current',    value: '118 µA/MHz typical' },
    { label: 'LPM3 (VLO)',        value: '500 nA' },
    { label: 'LPM3.5 (RTC)',      value: '350 nA' },
    { label: 'LPM4.5',            value: '45 nA' },
    { label: 'I/O Pins',          value: '68 (P1–P8, PJ), all interrupt-capable' },
    { label: 'ADC12_B',           value: '12-bit, 20 external + 2 internal channels, 200 ksps' },
    { label: 'LEA',               value: 'Low-Energy Accelerator: 256-pt FFT 40x faster than SW' },
    { label: 'Timers',            value: 'TB0 (7 CCR), TA0 (3 CCR), TA1 (3 CCR), TA4 (3 CCR)' },
    { label: 'eUSCI_A (x4)',      value: 'UART, IrDA, SPI (A0–A3)' },
    { label: 'eUSCI_B (x4)',      value: 'I2C, SPI (B0–B3)' },
    { label: 'Comparator_E',      value: '16 inputs, programmable reference' },
    { label: 'AES',               value: '128/256-bit hardware encryption accelerator' },
    { label: 'DMA',               value: '6-channel controller' },
    { label: 'RTC_C',             value: 'Real-Time Clock with calendar, alarm, and temp compensation' },
    { label: 'Programming',       value: 'Spy-Bi-Wire (2-pin) and JTAG (4-pin)' },
    { label: 'Operating Temp',    value: '-40 to +85 °C' }
  ],

  // ── KEY FEATURES (Datasheet tab list) ────────────────────────
  dsFeatures: [
    '256 KB unified FRAM: ultra-low-power writes, 10¹⁵ write endurance, single-bit error correction',
    'Low-Energy Accelerator (LEA): DSP-like performance for FFT, FIR, and matrix operations — 40x faster than software',
    '4x eUSCI_A (UART/IrDA/SPI) + 4x eUSCI_B (I2C/SPI) — up to 8 serial interfaces',
    'ADC12_B: 12-bit SAR, 200 ksps, 20 external + 2 internal channels, differential mode',
    'TimerB0 with 7 capture/compare registers + TimerA0, TimerA1, TimerA4 with 3 CCRs each',
    'Comp_E comparator with 16 inputs and slope A/D conversion for capacitive sensing',
    '128/256-bit AES hardware accelerator with DMA support for secure communication',
    '6-channel DMA controller for background data transfers between memories/peripherals',
    'RTC_C with calendar, alarm, and 32.768 kHz crystal support',
    'JTAG (4-pin) and Spy-Bi-Wire (2-pin) debug and programming',
    'Hardware UART or I2C bootloader (BSL) — field-updateable',
    'All GPIO pins support capacitive-touch sensing without external components',
    'MPY32 hardware multiplier supports 32×32-bit operations (unsigned, signed, MAC)',
    'Ultra-low-power: 118 µA/MHz active, 45 nA in LPM4.5',
    'Typical applications: metering, industrial sensors, handheld instrumentation, hearing aids, wearables'
  ]
};